package org.opentrafficsim.road.gtu.lane.tactical.mirova.following;

import java.util.function.Supplier;

import org.opentrafficsim.base.parameters.ParameterException;
import org.opentrafficsim.base.parameters.ParameterSet;
import org.opentrafficsim.base.parameters.Parameters;
import org.opentrafficsim.road.gtu.lane.tactical.following.CarFollowingModelFactory;

import nl.tudelft.simulation.jstats.distributions.DistContinuous;
import nl.tudelft.simulation.jstats.distributions.DistNormal;
import nl.tudelft.simulation.jstats.streams.StreamInterface;

/**
 * Factory for generating {@link AbstractWiedemannModel} instances and their associated parameter sets.
 * <p>
 * This factory is responsible for instantiating the specific Wiedemann car-following models
 * and initializing their stochastic parameters, such as the normally distributed
 * {@code FSPEED} (desired speed factor).
 * </p>
 * <p>
 * Copyright (c) 2025 Marvin Baumann / KIT. All rights reserved. <br>
 * BSD-style license. See <a href="https://opentrafficsim.org/docs/license.html">OpenTrafficSim License</a>.
 * </p>
 *
 * @param <T> the specific type of AbstractWiedemannModel generated by this factory
 * @author <a href="https://github.com/baumarv">Marvin Baumann</a>
 */
public class AbstractWiedemannFactory<T extends AbstractWiedemannModel> implements CarFollowingModelFactory<T>
{

    /** Supplier for creating new instances of the specific Wiedemann model. */
    private final Supplier<T> wiedemann;

    /** Continuous distribution for the fSpeed (desired speed factor) parameter. */
    private final DistContinuous fSpeed;

    /** The random number stream used for stochastic parameter generation. */
    private final StreamInterface randomStream;

    /**
     * Constructs a new factory for Wiedemann car-following models.
     *
     * @param wiedemann    supplier providing instances of the specific Wiedemann model
     * @param randomStream random number stream for drawing stochastic parameters
     */
    public AbstractWiedemannFactory(final Supplier<T> wiedemann, final StreamInterface randomStream)
    {
        this.wiedemann = wiedemann;
        this.randomStream = randomStream;
        // Initialize fSpeed with a normal distribution: Mean = ~1.0308, SD = 0.1
        this.fSpeed = new DistNormal(randomStream, 123.7 / 120.0, 0.1);
    }

    /**
     * Generates a new instance of the car-following model.
     *
     * @return a new Wiedemann car-following model instance
     */
    @Override
    public final T generateCarFollowingModel()
    {
        return this.wiedemann.get();
    }

    /**
     * Generates the default parameter set for the Wiedemann model, including randomly drawn stochastic parameters.
     *
     * @return a fully initialized parameter set
     * @throws ParameterException if setting a parameter fails
     */
    @Override
    public Parameters getParameters() throws ParameterException
    {
        ParameterSet parameters = new ParameterSet();
        parameters.setDefaultParameters(AbstractWiedemannModel.class);

        // Draw a fresh stochastic speed factor for this specific parameter set
        parameters.setParameter(AbstractWiedemannModel.FSPEED, this.fSpeed.draw());

        return parameters;
    }
}