package org.opentrafficsim.core.value.vdouble.matrix;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.Set;

import org.junit.Test;
import org.opentrafficsim.core.unit.AreaUnit;
import org.opentrafficsim.core.unit.LengthUnit;
import org.opentrafficsim.core.unit.SIUnit;
import org.opentrafficsim.core.unit.SpeedUnit;
import org.opentrafficsim.core.unit.TemperatureUnit;
import org.opentrafficsim.core.unit.TimeUnit;
import org.opentrafficsim.core.unit.Unit;
import org.opentrafficsim.core.value.Absolute;
import org.opentrafficsim.core.value.Relative;
import org.opentrafficsim.core.value.ValueException;
import org.opentrafficsim.core.value.vdouble.scalar.DoubleScalar;

/**
 * Test the DoubleMatrix class.
 * <p>
 * This file was generated by the OpenTrafficSim value test classes generator, 30 dec, 2014
 * <p>
 * Copyright (c) 2014 Delft University of Technology, PO Box 5, 2600 AA, Delft, the Netherlands. All rights reserved. <br>
 * BSD-style license. See <a href="http://opentrafficsim.org/node/13">OpenTrafficSim License</a>.
 * <p>
 * @version 30 dec, 2014 <br>
 * @author <a href="http://www.tbm.tudelft.nl/averbraeck">Alexander Verbraeck</a>
 * @author <a href="http://www.tudelft.nl/pknoppers">Peter Knoppers</a>
 */
public class DoubleMatrixDenseTest
{
    /**
     * Generate test data.
     * @param rows int; the number of rows in the result
     * @param columns int; the number of columns in the result
     * @param nonRectangular boolean; if true; return a non-rectangular array; if false; return a rectangular array
     * @param startValue double; seed value
     * @return double[][]
     */
    private static double[][] data(final int rows, final int columns, final boolean nonRectangular,
            final double startValue)
    {
        double[][] result = new double[rows][];
        final int badRowIndex = nonRectangular ? rows - 1 : -1;
        for (int row = 0; row < rows; row++)
        {
            result[row] = new double[row == badRowIndex ? columns + 1 : columns];
            for (int column = 0; column < result[row].length; column++)
            {
                result[row][column] = row * 1000 + column + startValue;
            }
        }
        return result;
    }

    /**
     * Check that the values in a DoubleMatrixmatch the expected values.
     * @param dm DoubleMatrix&lt;?&gt;; the DoubleMatrix to match
     * @param reference double[][]; the reference values
     * @param precision double; the maximum allowed error
     * @param u Unit&lt;?&gt;; the expected type
     * @param expectAbsolute boolean; if true; dm should be Absolute; if false; dm should be Relative
     */
    private static void checkContentsAndType(final DoubleMatrix<?> dm, final double[][] reference,
            final double precision, final Unit<?> u, final boolean expectAbsolute)
    {
        assertTrue("DoubleMatrix should not be null", null != dm);
        for (int row = dm.rows(); --row >= 0;)
        {
            for (int column = dm.columns(); --column >= 0;)
                {
                try
                {
                    assertEquals("Value should match", reference[row][column], dm.getInUnit(row, column), precision);
                }
                catch (ValueException exception)
                {
                    fail("Unexpected exception");
                }
            }
        }
        assertEquals("Unit should be " + u.toString(), u, dm.getUnit());
        assertTrue("Should be " + (expectAbsolute ? "Absolute" : "Relative"), 
                    expectAbsolute ? dm.isAbsolute() : dm.isRelative());
    }

    /**
     * Test that the toString method returns something sensible.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toStringAbsTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.KELVIN;
            double[][] value = data(3, 5, false, 38.0);
            DoubleMatrix.Abs.Dense<TemperatureUnit> dm = new DoubleMatrix.Abs.Dense<TemperatureUnit>(value, tempUnit);
            String result = dm.toString(true);
            assertTrue("toString result contains \" Abs \"", result.contains(" Abs "));
            assertTrue("toString result contains \"[K]\"", result.contains("[K]"));
            assertTrue("toString result starts with \"Immutable \"", result.startsWith("Immutable"));
            assertTrue("toString contains \"Dense\"", result.contains("Dense"));
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test that the toString method returns something sensible.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toStringMutableAbsTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.KELVIN;
            double[][] value = data(3, 5, false, 38.0);
            MutableDoubleMatrix.Abs.Dense<TemperatureUnit> dm = new MutableDoubleMatrix.Abs.Dense<TemperatureUnit>(value, tempUnit);
            String result = dm.toString(true);
            assertTrue("toString result contains \" Abs \"", result.contains(" Abs "));
            assertTrue("toString result contains \"[K]\"", result.contains("[K]"));
            assertTrue("toString result starts with \"Immutable \"", result.startsWith("Mutable"));
            assertTrue("toString contains \"Dense\"", result.contains("Dense"));
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test constructor, verify the various fields in the constructed objects, test conversions to related units.
     */
    @SuppressWarnings({"static-method", "unchecked"})
    @Test
    public final void basicsAbsTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.DEGREE_CELSIUS;
            double[][] value = data(3, 5, false, 38.0);
            DoubleMatrix.Abs.Dense<TemperatureUnit> temperatureDM = new DoubleMatrix.Abs.Dense<TemperatureUnit>(value, tempUnit);
            checkContentsAndType(temperatureDM, value, 0.001, tempUnit, true);
            assertEquals("Value in SI is equivalent in Kelvin", 311.15, temperatureDM.getSI(0, 0), 0.05);
            assertEquals("Value in Fahrenheit", 100.4, temperatureDM.getInUnit(0, 0, TemperatureUnit.DEGREE_FAHRENHEIT), 0.1);
            double[][] out = temperatureDM.getValuesInUnit();
            for (int row = 0; row < value.length; row++)
            {
                for (int column = 0; column < value[row].length; column++)
                {
                    assertEquals("Value should match", value[row][column], out[row][column], 0.001);
                }
            }
            MutableDoubleMatrix.Abs.Dense<TemperatureUnit> mdm = new MutableDoubleMatrix.Abs.Dense<TemperatureUnit>(value, tempUnit);
            checkContentsAndType(mdm, value, 0.001, tempUnit, true);
            mdm.setSI(0, 0, 73);
            double safe = value[0][0];
            value[0][0] = -200; // Approximate Celsius equivalent of 73 Kelvin
            checkContentsAndType(mdm, value, 1, tempUnit, true);
            value[0][0] = safe; // Restore
            mdm.set(0, 0, temperatureDM.get(0, 0));
            checkContentsAndType(mdm, value, 0.001, tempUnit, true);
            DoubleMatrix.Abs.Dense<TemperatureUnit> temperature2DM = new DoubleMatrix.Abs.Dense<TemperatureUnit>(temperatureDM.getMatrixSI(), TemperatureUnit.KELVIN);
            assertTrue("temperature2DM should be equal to temperatureDM", temperature2DM.equals(temperatureDM));
            assertTrue("Value is Absolute", temperatureDM.isAbsolute());
            assertFalse("Value is not Relative", temperatureDM.isRelative());
            temperatureDM = new DoubleMatrix.Abs.Dense<TemperatureUnit>(value, TemperatureUnit.KELVIN);
            checkContentsAndType(temperatureDM, value, 0.001, TemperatureUnit.KELVIN, true);
            out = temperatureDM.getValuesSI();
            for (int row = 0; row < value.length; row++)
            {
                for (int column = 0; column < value[row].length; column++)
                {
                    assertEquals("Value should match", value[row][column], out[row][column], 0.001);
                }
            }
            DoubleScalar.Abs<TemperatureUnit>[][] scalar = new DoubleScalar.Abs[value.length][];
        for (int row = 0; row < value.length; row++)
            {
                scalar[row] = new DoubleScalar.Abs[value[row].length];
                for (int column = 0; column < value[row].length; column++)
                {
                    scalar[row][column] = new DoubleScalar.Abs<TemperatureUnit>(value[row][column], TemperatureUnit.DEGREE_CELSIUS);
                }
            }
            temperatureDM = new DoubleMatrix.Abs.Dense<TemperatureUnit>(scalar);
            checkContentsAndType(temperatureDM, value, 0.001, tempUnit, true);
            assertEquals("All cells != 0; cardinality should equal number of cells", value.length * value[0].length, temperatureDM.cardinality());
            double sum = 0;
            for (int row = 0; row < value.length; row++)
            {
                scalar[row] = new DoubleScalar.Abs[value[row].length];
                for (int column = 0; column < value[row].length; column++)
                {
                    sum += temperatureDM.getSI(row, column);
                }
            }
            assertEquals("zSum should be sum of all values", sum, temperatureDM.zSum(), 0.001);
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test conversion to mutable equivalent and back.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toMutableAndBackAbsTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.DEGREE_CELSIUS;
            double[][] value = data(3, 5, false, 38.0);
            double[][] value2 = data(3, 5, false, 38.0);
            value2[0][0] = 12345;
            DoubleMatrix.Abs.Dense<TemperatureUnit> dm = new DoubleMatrix.Abs.Dense<TemperatureUnit>(value, tempUnit);
            DoubleMatrix.Abs<TemperatureUnit> dmCopy = dm.copy();
            MutableDoubleMatrix.Abs.Dense<TemperatureUnit> mdm = dm.mutable();
            checkContentsAndType(dm, value, 0.001, tempUnit, true);
            checkContentsAndType(mdm, value, 0.001, tempUnit, true);
            checkContentsAndType(dmCopy, value, 0.001, tempUnit, true);
            MutableDoubleMatrix.Abs.Dense<TemperatureUnit> mdmCopy = mdm.copy();
            checkContentsAndType(mdmCopy, value, 0.001, tempUnit, true);
            MutableDoubleMatrix.Abs.Dense<TemperatureUnit> mmdm = mdm.mutable();
            checkContentsAndType(mmdm, value, 0.001, tempUnit, true);
            assertEquals("hashCode is independent on mutability", dm.hashCode(), mdm.hashCode());
            // Modify mdm
            mdm.setInUnit(0, 0, 12345, TemperatureUnit.DEGREE_CELSIUS);
            checkContentsAndType(dm, value, 0.001, tempUnit, true);
            checkContentsAndType(mdm, value2, 0.01, tempUnit, true);
            checkContentsAndType(mdmCopy, value, 0.001, tempUnit, true);
            checkContentsAndType(mmdm, value, 0.001, tempUnit, true);
            DoubleMatrix.Abs<TemperatureUnit> idm = mdm.immutable();
            assertTrue("Different value extremely likely results in different hashCode", dm.hashCode() != mdm.hashCode());
            // Restore value of mdm
            mdm.setSI(0, 0, dm.getSI(0, 0));
            checkContentsAndType(idm, value2, 0.01, tempUnit, true);
            checkContentsAndType(mdm, value, 0.001, tempUnit, true);
            checkContentsAndType(mmdm, value, 0.001, tempUnit, true);
            mmdm.setSI(0, 0, 0);
            checkContentsAndType(mdm, value, 0.001, tempUnit, true);
            assertEquals("value should be about -273", -273, mmdm.getInUnit(0, 0, tempUnit), 0.2);
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test the equals method.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void equalsAbsTest()
    {
        LengthUnit lengthUnit = LengthUnit.METER;
        double value = 38.0;
        DoubleScalar.Abs<LengthUnit> dm = new DoubleScalar.Abs<LengthUnit>(value, lengthUnit);
        assertTrue("Equal to itself", dm.equals(dm));
        assertFalse("Not equal to null", dm.equals(null));
        assertFalse("Not equal to some other kind of object; e.g. a String", dm.equals(new String("abc")));
        DoubleScalar.Rel<LengthUnit> dmCounterPart = new DoubleScalar.Rel<LengthUnit>(value, lengthUnit);
        assertFalse("Not equal if one Absolute and other Relative", dm.equals(dmCounterPart));
        DoubleScalar.Abs<TemperatureUnit> dmWrongBaseUnit = new DoubleScalar.Abs<TemperatureUnit>(value, TemperatureUnit.KELVIN);
        assertEquals("The underlying SI values are the same", dm.getSI(), dmWrongBaseUnit.getSI(), 0.0001);
        assertFalse("Not equals because the standard SI unit differs", dm.equals(dmWrongBaseUnit));
        DoubleScalar.Abs<LengthUnit> dmCompatibleUnit =
                new DoubleScalar.Abs<LengthUnit>(38000.0, LengthUnit.MILLIMETER);
        assertFalse("Units are different", dm.getUnit().equals(dmCompatibleUnit.getUnit()));
        assertTrue("equals returns true", dm.equals(dmCompatibleUnit));
        DoubleScalar.Abs<LengthUnit> dmDifferentValue =
                new DoubleScalar.Abs<LengthUnit>(123.456, LengthUnit.MILLIMETER);
        assertFalse("Different value makes equals return false", dm.equals(dmDifferentValue));
    }

    /**
     * Test the Math functions.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void mathFunctionsTestAbsTest()
    {
        double[] seedValues = {-10, -2, -1, -0.5, -0.1, 0, 0.1, 0.5, 1, 2, 10};
        for (double seedValue : seedValues)
        {
            double[][] input = data(3, 5, false, seedValue);
            MutableDoubleMatrix.Abs.Dense<LengthUnit> dm;
            try
            {
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.abs();
                MathTester.tester(input, "abs", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.abs(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.acos();
                MathTester.tester(input, "acos", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.acos(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.asin();
                MathTester.tester(input, "asin", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.asin(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.atan();
                MathTester.tester(input, "atan", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.atan(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.cbrt();
                MathTester.tester(input, "cbrt", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.cbrt(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.ceil();
                MathTester.tester(input, "ceil", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.ceil(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.cos();
                MathTester.tester(input, "cos", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.cos(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.cosh();
                MathTester.tester(input, "cosh", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.cosh(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.exp();
                MathTester.tester(input, "exp", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.exp(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.expm1();
                MathTester.tester(input, "expm1", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.expm1(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.floor();
                MathTester.tester(input, "floor", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.floor(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.log();
                MathTester.tester(input, "log", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.log(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.log10();
                MathTester.tester(input, "log10", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.log10(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.log1p();
                MathTester.tester(input, "log1p", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.log1p(d);
                    }
                });
            for (int i = -10; i <= 10; i++)
            {
                final double exponent = i * 0.5d;
                    dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                    dm.pow(exponent);
                    MathTester.tester(input, "pow(" + exponent + ")", dm, 0.001, new DoubleToDouble()
                    {
                        @Override
                        public double function(final double d)
                        {
                            return Math.pow(d, exponent);
                        }
                    });
            }
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.rint();
                MathTester.tester(input, "rint", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.rint(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.round();
                MathTester.tester(input, "round", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.round(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.signum();
                MathTester.tester(input, "signum", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.signum(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.sin();
                MathTester.tester(input, "sin", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.sin(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.sinh();
                MathTester.tester(input, "sinh", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.sinh(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.sqrt();
                MathTester.tester(input, "sqrt", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.sqrt(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.tan();
                MathTester.tester(input, "tan", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.tan(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.tanh();
                MathTester.tester(input, "tanh", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.tanh(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.toDegrees();
                MathTester.tester(input, "toDegrees", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.toDegrees(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.toRadians();
                MathTester.tester(input, "toRadians", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.toRadians(d);
                    }
                });
                dm = new MutableDoubleMatrix.Abs.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.inv();
                MathTester.tester(input, "inv", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return 1 / d;
                    }
                });
            }
            catch (ValueException ve)
            {
                fail("Caught unexpected ValueException: " + ve.toString());
            }
        }
    }

    /**
     * Test plus(DoubleMatrixAbs.Dense, DoubleMatrixRel.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryplusOfAbsDenseAndRelDenseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Abs.Dense<LengthUnit> left = new DoubleMatrix.Abs.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Rel.Dense<LengthUnit> right = new DoubleMatrix.Rel.Dense<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Abs.Dense<?> result = DoubleMatrix.plus(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI plus of contributing elements", left.getSI(i, j) + right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test minus(DoubleMatrixAbs.Dense, DoubleMatrixRel.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryminusOfAbsDenseAndRelDenseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Abs.Dense<LengthUnit> left = new DoubleMatrix.Abs.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Rel.Dense<LengthUnit> right = new DoubleMatrix.Rel.Dense<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Abs.Dense<?> result = DoubleMatrix.minus(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI minus of contributing elements", left.getSI(i, j) - right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test times(DoubleMatrixAbs.Dense, DoubleMatrixAbs.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binarytimesOfAbsDenseAndAbsDenseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Abs.Dense<LengthUnit> left = new DoubleMatrix.Abs.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Abs.Dense<LengthUnit> right = new DoubleMatrix.Abs.Dense<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Abs.Dense<?> result = DoubleMatrix.times(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI times of contributing elements", left.getSI(i, j) * right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test plus(DoubleMatrixAbs.Dense, DoubleMatrixRel.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryplusOfAbsDenseAndRelSparseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Abs.Dense<LengthUnit> left = new DoubleMatrix.Abs.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Rel.Sparse<LengthUnit> right = new DoubleMatrix.Rel.Sparse<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Abs.Dense<?> result = DoubleMatrix.plus(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI plus of contributing elements", left.getSI(i, j) + right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test minus(DoubleMatrixAbs.Dense, DoubleMatrixRel.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryminusOfAbsDenseAndRelSparseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Abs.Dense<LengthUnit> left = new DoubleMatrix.Abs.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Rel.Sparse<LengthUnit> right = new DoubleMatrix.Rel.Sparse<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Abs.Dense<?> result = DoubleMatrix.minus(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI minus of contributing elements", left.getSI(i, j) - right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test times(DoubleMatrixAbs.Dense, DoubleMatrixAbs.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binarytimesOfAbsDenseAndAbsSparseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Abs.Dense<LengthUnit> left = new DoubleMatrix.Abs.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Abs.Sparse<LengthUnit> right = new DoubleMatrix.Abs.Sparse<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Abs.Sparse<?> result = DoubleMatrix.times(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI times of contributing elements", left.getSI(i, j) * right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test that malformed or mismatching arrays throw a ValueException.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void sizeCheckAbsTest()
    {
        int junk = 0;
        try
        {
            // null array
            new DoubleMatrix.Abs.Dense<TemperatureUnit>((double[][]) null, TemperatureUnit.DEGREE_FAHRENHEIT);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        try
        {
            // Matrix with null on first row
            double[][] in = data(3, 5, false, 12.3);
            in[0] = null;
            new DoubleMatrix.Abs.Dense<TemperatureUnit>(in, TemperatureUnit.DEGREE_CELSIUS);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        try
        {
            // Matrix with null on last row
            double[][] in = data(3, 5, false, 12.3);
            in[in.length - 1] = null;
            new DoubleMatrix.Abs.Dense<TemperatureUnit>(in, TemperatureUnit.DEGREE_CELSIUS);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        try
        {
            // Non-rectangular array
            double[][] in = data(3, 5, true, 12.3);
            new DoubleMatrix.Abs.Dense<TemperatureUnit>(in, TemperatureUnit.DEGREE_CELSIUS);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        // Determinant of non-square Matrix
        double[][] in = data(3, 5, false, 12.3);
        try
        {
            DoubleMatrix.Abs.Dense<TemperatureUnit> matrix = null;
            try
            {
                matrix = new DoubleMatrix.Abs.Dense<TemperatureUnit>(in, TemperatureUnit.DEGREE_CELSIUS);
            }
            catch (ValueException ve)
            {
                fail("Caught unexpected exception: " + ve.toString());
            }
            matrix.det();
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        try
        {
            DoubleMatrix.Abs.Dense<TemperatureUnit> matrix = null;
            double[][] rowCountWrong = null;
            try
            {
                matrix = new DoubleMatrix.Abs.Dense<TemperatureUnit>(in, TemperatureUnit.DEGREE_CELSIUS);
                 rowCountWrong = data(4, 5, false, 2);
            }
            catch (ValueException ve)
            {
                fail("Caught unexpected exception: " + ve.toString());
            }
            DoubleMatrix.times(matrix, rowCountWrong);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        assertTrue("The variable junk is only used to suppress annoying warnings of the code checker", junk > 0);
    }

    /**
     * Test the det method that computes and returns the determinant.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void determinantAbsTest()
    {
        try
        {
            double[][] values = {{1, 2, 3 }, {3, 5, 7 }, {5, 10, 0} };
            DoubleMatrix.Abs.Dense<TemperatureUnit> matrix = new DoubleMatrix.Abs.Dense<TemperatureUnit>(values, TemperatureUnit.KELVIN);
            assertEquals("Determinant should be 15", 15, matrix.det(), 0.001);
        }
        catch (ValueException ve)
        {
            if (ve.toString().contains("Matrix must be sparse"))
            {
                System.err.println("Ignoring bug in COLT library");
                return;
            }
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test that the times methods with a simple array as the 2nd argument.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void scaleAbsTest()
    {
        try
        {
            double[][] leftIn = data(3, 5, false, -12.34);
            DoubleMatrix.Abs.Dense<TemperatureUnit> left = new DoubleMatrix.Abs.Dense<TemperatureUnit>(leftIn, TemperatureUnit.KELVIN);
            double[][] right = data(3, 5, false, -4.321);
            MutableDoubleMatrix.Abs.Dense<TemperatureUnit> result = DoubleMatrix.times(left, right);
            assertEquals("Result should be in Kelvin", TemperatureUnit.KELVIN, result.getUnit());
            for (int row = right.length; --row >= 0;)
            {
                for (int column = right[row].length; --column >= 0;)
                {
                    assertEquals("Content should match product of left and right", leftIn[row][column] * right[row][column], result.getSI(row, column), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test that the toString method returns something sensible.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toStringRelTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.KELVIN;
            double[][] value = data(3, 5, false, 38.0);
            DoubleMatrix.Rel.Dense<TemperatureUnit> dm = new DoubleMatrix.Rel.Dense<TemperatureUnit>(value, tempUnit);
            String result = dm.toString(true);
            assertTrue("toString result contains \" Rel \"", result.contains(" Rel "));
            assertTrue("toString result contains \"[K]\"", result.contains("[K]"));
            assertTrue("toString result starts with \"Immutable \"", result.startsWith("Immutable"));
            assertTrue("toString contains \"Dense\"", result.contains("Dense"));
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test that the toString method returns something sensible.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toStringMutableRelTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.KELVIN;
            double[][] value = data(3, 5, false, 38.0);
            MutableDoubleMatrix.Rel.Dense<TemperatureUnit> dm = new MutableDoubleMatrix.Rel.Dense<TemperatureUnit>(value, tempUnit);
            String result = dm.toString(true);
            assertTrue("toString result contains \" Rel \"", result.contains(" Rel "));
            assertTrue("toString result contains \"[K]\"", result.contains("[K]"));
            assertTrue("toString result starts with \"Immutable \"", result.startsWith("Mutable"));
            assertTrue("toString contains \"Dense\"", result.contains("Dense"));
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test constructor, verify the various fields in the constructed objects, test conversions to related units.
     */
    @SuppressWarnings({"static-method", "unchecked"})
    @Test
    public final void basicsRelTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.DEGREE_CELSIUS;
            double[][] value = data(3, 5, false, 38.0);
            DoubleMatrix.Rel.Dense<TemperatureUnit> temperatureDM = new DoubleMatrix.Rel.Dense<TemperatureUnit>(value, tempUnit);
            checkContentsAndType(temperatureDM, value, 0.001, tempUnit, false);
            assertEquals("Value in SI is equivalent in Kelvin", 311.15, temperatureDM.getSI(0, 0), 0.05);
            assertEquals("Value in Fahrenheit", 100.4, temperatureDM.getInUnit(0, 0, TemperatureUnit.DEGREE_FAHRENHEIT), 0.1);
            double[][] out = temperatureDM.getValuesInUnit();
            for (int row = 0; row < value.length; row++)
            {
                for (int column = 0; column < value[row].length; column++)
                {
                    assertEquals("Value should match", value[row][column], out[row][column], 0.001);
                }
            }
            MutableDoubleMatrix.Rel.Dense<TemperatureUnit> mdm = new MutableDoubleMatrix.Rel.Dense<TemperatureUnit>(value, tempUnit);
            checkContentsAndType(mdm, value, 0.001, tempUnit, false);
            mdm.setSI(0, 0, 73);
            double safe = value[0][0];
            value[0][0] = -200; // Approximate Celsius equivalent of 73 Kelvin
            checkContentsAndType(mdm, value, 1, tempUnit, false);
            value[0][0] = safe; // Restore
            mdm.set(0, 0, temperatureDM.get(0, 0));
            checkContentsAndType(mdm, value, 0.001, tempUnit, false);
            DoubleMatrix.Rel.Dense<TemperatureUnit> temperature2DM = new DoubleMatrix.Rel.Dense<TemperatureUnit>(temperatureDM.getMatrixSI(), TemperatureUnit.KELVIN);
            assertTrue("temperature2DM should be equal to temperatureDM", temperature2DM.equals(temperatureDM));
            assertTrue("Value is Relative", temperatureDM.isRelative());
            assertFalse("Value is not Absolute", temperatureDM.isAbsolute());
            temperatureDM = new DoubleMatrix.Rel.Dense<TemperatureUnit>(value, TemperatureUnit.KELVIN);
            checkContentsAndType(temperatureDM, value, 0.001, TemperatureUnit.KELVIN, false);
            out = temperatureDM.getValuesSI();
            for (int row = 0; row < value.length; row++)
            {
                for (int column = 0; column < value[row].length; column++)
                {
                    assertEquals("Value should match", value[row][column], out[row][column], 0.001);
                }
            }
            DoubleScalar.Rel<TemperatureUnit>[][] scalar = new DoubleScalar.Rel[value.length][];
        for (int row = 0; row < value.length; row++)
            {
                scalar[row] = new DoubleScalar.Rel[value[row].length];
                for (int column = 0; column < value[row].length; column++)
                {
                    scalar[row][column] = new DoubleScalar.Rel<TemperatureUnit>(value[row][column], TemperatureUnit.DEGREE_CELSIUS);
                }
            }
            temperatureDM = new DoubleMatrix.Rel.Dense<TemperatureUnit>(scalar);
            checkContentsAndType(temperatureDM, value, 0.001, tempUnit, false);
            assertEquals("All cells != 0; cardinality should equal number of cells", value.length * value[0].length, temperatureDM.cardinality());
            double sum = 0;
            for (int row = 0; row < value.length; row++)
            {
                scalar[row] = new DoubleScalar.Rel[value[row].length];
                for (int column = 0; column < value[row].length; column++)
                {
                    sum += temperatureDM.getSI(row, column);
                }
            }
            assertEquals("zSum should be sum of all values", sum, temperatureDM.zSum(), 0.001);
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test conversion to mutable equivalent and back.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toMutableAndBackRelTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.DEGREE_CELSIUS;
            double[][] value = data(3, 5, false, 38.0);
            double[][] value2 = data(3, 5, false, 38.0);
            value2[0][0] = 12345;
            DoubleMatrix.Rel.Dense<TemperatureUnit> dm = new DoubleMatrix.Rel.Dense<TemperatureUnit>(value, tempUnit);
            DoubleMatrix.Rel<TemperatureUnit> dmCopy = dm.copy();
            MutableDoubleMatrix.Rel.Dense<TemperatureUnit> mdm = dm.mutable();
            checkContentsAndType(dm, value, 0.001, tempUnit, false);
            checkContentsAndType(mdm, value, 0.001, tempUnit, false);
            checkContentsAndType(dmCopy, value, 0.001, tempUnit, false);
            MutableDoubleMatrix.Rel.Dense<TemperatureUnit> mdmCopy = mdm.copy();
            checkContentsAndType(mdmCopy, value, 0.001, tempUnit, false);
            MutableDoubleMatrix.Rel.Dense<TemperatureUnit> mmdm = mdm.mutable();
            checkContentsAndType(mmdm, value, 0.001, tempUnit, false);
            assertEquals("hashCode is independent on mutability", dm.hashCode(), mdm.hashCode());
            // Modify mdm
            mdm.setInUnit(0, 0, 12345, TemperatureUnit.DEGREE_CELSIUS);
            checkContentsAndType(dm, value, 0.001, tempUnit, false);
            checkContentsAndType(mdm, value2, 0.01, tempUnit, false);
            checkContentsAndType(mdmCopy, value, 0.001, tempUnit, false);
            checkContentsAndType(mmdm, value, 0.001, tempUnit, false);
            DoubleMatrix.Rel<TemperatureUnit> idm = mdm.immutable();
            assertTrue("Different value extremely likely results in different hashCode", dm.hashCode() != mdm.hashCode());
            // Restore value of mdm
            mdm.setSI(0, 0, dm.getSI(0, 0));
            checkContentsAndType(idm, value2, 0.01, tempUnit, false);
            checkContentsAndType(mdm, value, 0.001, tempUnit, false);
            checkContentsAndType(mmdm, value, 0.001, tempUnit, false);
            mmdm.setSI(0, 0, 0);
            checkContentsAndType(mdm, value, 0.001, tempUnit, false);
            assertEquals("value should be about -273", -273, mmdm.getInUnit(0, 0, tempUnit), 0.2);
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test the equals method.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void equalsRelTest()
    {
        LengthUnit lengthUnit = LengthUnit.METER;
        double value = 38.0;
        DoubleScalar.Rel<LengthUnit> dm = new DoubleScalar.Rel<LengthUnit>(value, lengthUnit);
        assertTrue("Equal to itself", dm.equals(dm));
        assertFalse("Not equal to null", dm.equals(null));
        assertFalse("Not equal to some other kind of object; e.g. a String", dm.equals(new String("abc")));
        DoubleScalar.Abs<LengthUnit> dmCounterPart = new DoubleScalar.Abs<LengthUnit>(value, lengthUnit);
        assertFalse("Not equal if one Absolute and other Relative", dm.equals(dmCounterPart));
        DoubleScalar.Rel<TemperatureUnit> dmWrongBaseUnit = new DoubleScalar.Rel<TemperatureUnit>(value, TemperatureUnit.KELVIN);
        assertEquals("The underlying SI values are the same", dm.getSI(), dmWrongBaseUnit.getSI(), 0.0001);
        assertFalse("Not equals because the standard SI unit differs", dm.equals(dmWrongBaseUnit));
        DoubleScalar.Rel<LengthUnit> dmCompatibleUnit =
                new DoubleScalar.Rel<LengthUnit>(38000.0, LengthUnit.MILLIMETER);
        assertFalse("Units are different", dm.getUnit().equals(dmCompatibleUnit.getUnit()));
        assertTrue("equals returns true", dm.equals(dmCompatibleUnit));
        DoubleScalar.Rel<LengthUnit> dmDifferentValue =
                new DoubleScalar.Rel<LengthUnit>(123.456, LengthUnit.MILLIMETER);
        assertFalse("Different value makes equals return false", dm.equals(dmDifferentValue));
    }

    /**
     * Test the Math functions.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void mathFunctionsTestRelTest()
    {
        double[] seedValues = {-10, -2, -1, -0.5, -0.1, 0, 0.1, 0.5, 1, 2, 10};
        for (double seedValue : seedValues)
        {
            double[][] input = data(3, 5, false, seedValue);
            MutableDoubleMatrix.Rel.Dense<LengthUnit> dm;
            try
            {
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.abs();
                MathTester.tester(input, "abs", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.abs(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.acos();
                MathTester.tester(input, "acos", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.acos(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.asin();
                MathTester.tester(input, "asin", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.asin(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.atan();
                MathTester.tester(input, "atan", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.atan(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.cbrt();
                MathTester.tester(input, "cbrt", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.cbrt(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.ceil();
                MathTester.tester(input, "ceil", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.ceil(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.cos();
                MathTester.tester(input, "cos", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.cos(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.cosh();
                MathTester.tester(input, "cosh", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.cosh(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.exp();
                MathTester.tester(input, "exp", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.exp(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.expm1();
                MathTester.tester(input, "expm1", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.expm1(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.floor();
                MathTester.tester(input, "floor", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.floor(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.log();
                MathTester.tester(input, "log", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.log(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.log10();
                MathTester.tester(input, "log10", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.log10(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.log1p();
                MathTester.tester(input, "log1p", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.log1p(d);
                    }
                });
            for (int i = -10; i <= 10; i++)
            {
                final double exponent = i * 0.5d;
                    dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                    dm.pow(exponent);
                    MathTester.tester(input, "pow(" + exponent + ")", dm, 0.001, new DoubleToDouble()
                    {
                        @Override
                        public double function(final double d)
                        {
                            return Math.pow(d, exponent);
                        }
                    });
            }
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.rint();
                MathTester.tester(input, "rint", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.rint(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.round();
                MathTester.tester(input, "round", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.round(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.signum();
                MathTester.tester(input, "signum", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.signum(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.sin();
                MathTester.tester(input, "sin", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.sin(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.sinh();
                MathTester.tester(input, "sinh", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.sinh(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.sqrt();
                MathTester.tester(input, "sqrt", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.sqrt(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.tan();
                MathTester.tester(input, "tan", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.tan(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.tanh();
                MathTester.tester(input, "tanh", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.tanh(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.toDegrees();
                MathTester.tester(input, "toDegrees", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.toDegrees(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.toRadians();
                MathTester.tester(input, "toRadians", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return Math.toRadians(d);
                    }
                });
                dm = new MutableDoubleMatrix.Rel.Dense<LengthUnit>(input, LengthUnit.METER);
                dm.inv();
                MathTester.tester(input, "inv", dm, 0.001, new DoubleToDouble()
                {
                    @Override
                    public double function(final double d)
                    {
                        return 1 / d;
                    }
                });
            }
            catch (ValueException ve)
            {
                fail("Caught unexpected ValueException: " + ve.toString());
            }
        }
    }

    /**
     * Test plus(DoubleMatrixRel.Dense, DoubleMatrixRel.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryplusOfRelDenseAndRelDenseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Rel.Dense<LengthUnit> left = new DoubleMatrix.Rel.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Rel.Dense<LengthUnit> right = new DoubleMatrix.Rel.Dense<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Rel.Dense<?> result = DoubleMatrix.plus(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI plus of contributing elements", left.getSI(i, j) + right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test minus(DoubleMatrixRel.Dense, DoubleMatrixRel.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryminusOfRelDenseAndRelDenseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Rel.Dense<LengthUnit> left = new DoubleMatrix.Rel.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Rel.Dense<LengthUnit> right = new DoubleMatrix.Rel.Dense<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Rel.Dense<?> result = DoubleMatrix.minus(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI minus of contributing elements", left.getSI(i, j) - right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test times(DoubleMatrixRel.Dense, DoubleMatrixRel.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binarytimesOfRelDenseAndRelDenseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Rel.Dense<LengthUnit> left = new DoubleMatrix.Rel.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Rel.Dense<LengthUnit> right = new DoubleMatrix.Rel.Dense<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Rel.Dense<?> result = DoubleMatrix.times(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI times of contributing elements", left.getSI(i, j) * right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test plus(DoubleMatrixRel.Dense, DoubleMatrixRel.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryplusOfRelDenseAndRelSparseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Rel.Dense<LengthUnit> left = new DoubleMatrix.Rel.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Rel.Sparse<LengthUnit> right = new DoubleMatrix.Rel.Sparse<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Rel.Dense<?> result = DoubleMatrix.plus(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI plus of contributing elements", left.getSI(i, j) + right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test minus(DoubleMatrixRel.Dense, DoubleMatrixRel.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryminusOfRelDenseAndRelSparseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Rel.Dense<LengthUnit> left = new DoubleMatrix.Rel.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Rel.Sparse<LengthUnit> right = new DoubleMatrix.Rel.Sparse<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Rel.Dense<?> result = DoubleMatrix.minus(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI minus of contributing elements", left.getSI(i, j) - right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test times(DoubleMatrixRel.Dense, DoubleMatrixRel.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binarytimesOfRelDenseAndRelSparseTest()
    {
        try
        {
            double[][] leftValue = data(3, 5, false, 123.4);
            double[][] rightValue = data(3, 5, false, 234.5);
            DoubleMatrix.Rel.Dense<LengthUnit> left = new DoubleMatrix.Rel.Dense<LengthUnit>(leftValue, LengthUnit.MILE);
            DoubleMatrix.Rel.Sparse<LengthUnit> right = new DoubleMatrix.Rel.Sparse<LengthUnit>(rightValue, LengthUnit.MILE);
            MutableDoubleMatrix.Rel.Sparse<?> result = DoubleMatrix.times(left, right);
            for (int i = 0; i < leftValue.length; i++)
            {
                for (int j = 0; j < leftValue[i].length; j++)
                {
                    assertEquals("value of element should be SI times of contributing elements", left.getSI(i, j) * right.getSI(i, j), result.getSI(i, j), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test that malformed or mismatching arrays throw a ValueException.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void sizeCheckRelTest()
    {
        int junk = 0;
        try
        {
            // null array
            new DoubleMatrix.Rel.Dense<TemperatureUnit>((double[][]) null, TemperatureUnit.DEGREE_FAHRENHEIT);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        try
        {
            // Matrix with null on first row
            double[][] in = data(3, 5, false, 12.3);
            in[0] = null;
            new DoubleMatrix.Rel.Dense<TemperatureUnit>(in, TemperatureUnit.DEGREE_CELSIUS);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        try
        {
            // Matrix with null on last row
            double[][] in = data(3, 5, false, 12.3);
            in[in.length - 1] = null;
            new DoubleMatrix.Rel.Dense<TemperatureUnit>(in, TemperatureUnit.DEGREE_CELSIUS);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        try
        {
            // Non-rectangular array
            double[][] in = data(3, 5, true, 12.3);
            new DoubleMatrix.Rel.Dense<TemperatureUnit>(in, TemperatureUnit.DEGREE_CELSIUS);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        // Determinant of non-square Matrix
        double[][] in = data(3, 5, false, 12.3);
        try
        {
            DoubleMatrix.Rel.Dense<TemperatureUnit> matrix = null;
            try
            {
                matrix = new DoubleMatrix.Rel.Dense<TemperatureUnit>(in, TemperatureUnit.DEGREE_CELSIUS);
            }
            catch (ValueException ve)
            {
                fail("Caught unexpected exception: " + ve.toString());
            }
            matrix.det();
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        try
        {
            DoubleMatrix.Rel.Dense<TemperatureUnit> matrix = null;
            double[][] rowCountWrong = null;
            try
            {
                matrix = new DoubleMatrix.Rel.Dense<TemperatureUnit>(in, TemperatureUnit.DEGREE_CELSIUS);
                 rowCountWrong = data(4, 5, false, 2);
            }
            catch (ValueException ve)
            {
                fail("Caught unexpected exception: " + ve.toString());
            }
            DoubleMatrix.times(matrix, rowCountWrong);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        assertTrue("The variable junk is only used to suppress annoying warnings of the code checker", junk > 0);
    }

    /**
     * Test the det method that computes and returns the determinant.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void determinantRelTest()
    {
        try
        {
            double[][] values = {{1, 2, 3 }, {3, 5, 7 }, {5, 10, 0} };
            DoubleMatrix.Rel.Dense<TemperatureUnit> matrix = new DoubleMatrix.Rel.Dense<TemperatureUnit>(values, TemperatureUnit.KELVIN);
            assertEquals("Determinant should be 15", 15, matrix.det(), 0.001);
        }
        catch (ValueException ve)
        {
            if (ve.toString().contains("Matrix must be sparse"))
            {
                System.err.println("Ignoring bug in COLT library");
                return;
            }
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test that the times methods with a simple array as the 2nd argument.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void scaleRelTest()
    {
        try
        {
            double[][] leftIn = data(3, 5, false, -12.34);
            DoubleMatrix.Rel.Dense<TemperatureUnit> left = new DoubleMatrix.Rel.Dense<TemperatureUnit>(leftIn, TemperatureUnit.KELVIN);
            double[][] right = data(3, 5, false, -4.321);
            MutableDoubleMatrix.Rel.Dense<TemperatureUnit> result = DoubleMatrix.times(left, right);
            assertEquals("Result should be in Kelvin", TemperatureUnit.KELVIN, result.getUnit());
            for (int row = right.length; --row >= 0;)
            {
                for (int column = right[row].length; --column >= 0;)
                {
                    assertEquals("Content should match product of left and right", leftIn[row][column] * right[row][column], result.getSI(row, column), 0.001);
                }
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /** */
    interface DoubleToDouble
    {
        /**
         * @param d double; value
         * @return double value
         */
        double function(double d);
    }

    /** */
    abstract static class MathTester
    {
        /**
         * Test a math function.
         * @param inputValues double[][]; unprocessed value
         * @param operation String; description of method that is being tested
         * @param actualResult DoubleMatrix&lt;?&gt;; the actual result of the operation
         * @param precision double; expected accuracy
         * @param function DoubleToDouble; encapsulated function that converts one inputValue to an outputValue
         */
        public static void tester(final double[][] inputValues, final String operation,
                final DoubleMatrix<?> actualResult, final double precision, final DoubleToDouble function)
        {
            for (int i = 0; i < inputValues.length; i++)
            {
                for (int j = 0; j < inputValues[i].length; j++)
                {
                    double expectedResult = function.function(inputValues[i][j]);
                    double got = 0;
                    try
                    {
                        got = actualResult.getSI(i, j);
                    }
                    catch (ValueException ve)
                    {
                        fail("Caught unexpected exception: " + ve.toString());
                    }
                    String description =
                            String.format("%s(%f->%f should be equal to %f with precision %f", operation, inputValues[i][j],
                                    expectedResult, got, precision);
                    // System.out.println(description);
                    assertEquals(description, expectedResult, got, precision);
                }
            }
        }

    }

}
