//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.03 at 01:02:34 PM CET
//

package org.opentrafficsim.road.network.factory.vissim.xsd;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SPEEDLIMIT" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="GTUTYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="LEGALSPEEDLIMIT" type="{http://www.opentrafficsim.org/ots}SPEEDTYPE" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="LANE" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="SPEEDLIMIT" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="GTUTYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="LEGALSPEEDLIMIT" type="{http://www.opentrafficsim.org/ots}SPEEDTYPE" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;attribute name="NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="LANETYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="OFFSET" use="required" type="{http://www.opentrafficsim.org/ots}SIGNEDLENGTHTYPE" />
 *                   &lt;attribute name="WIDTH" type="{http://www.opentrafficsim.org/ots}LENGTHTYPE" />
 *                   &lt;attribute name="DIRECTION" use="required" type="{http://www.opentrafficsim.org/ots}DIRECTIONTYPE" />
 *                   &lt;attribute name="COLOR" type="{http://www.opentrafficsim.org/ots}COLORTYPE" />
 *                   &lt;attribute name="OVERTAKING" type="{http://www.opentrafficsim.org/ots}OVERTAKINGTYPE" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="NOTRAFFICLANE" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="OFFSET" use="required" type="{http://www.opentrafficsim.org/ots}SIGNEDLENGTHTYPE" />
 *                   &lt;attribute name="WIDTH" type="{http://www.opentrafficsim.org/ots}LENGTHTYPE" />
 *                   &lt;attribute name="COLOR" type="{http://www.opentrafficsim.org/ots}COLORTYPE" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="SHOULDER" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="OFFSET" use="required" type="{http://www.opentrafficsim.org/ots}SIGNEDLENGTHTYPE" />
 *                   &lt;attribute name="WIDTH" type="{http://www.opentrafficsim.org/ots}LENGTHTYPE" />
 *                   &lt;attribute name="COLOR" type="{http://www.opentrafficsim.org/ots}COLORTYPE" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="STRIPE" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="TYPE" use="required" type="{http://www.opentrafficsim.org/ots}STRIPETYPE" />
 *                   &lt;attribute name="OFFSET" use="required" type="{http://www.opentrafficsim.org/ots}SIGNEDLENGTHTYPE" />
 *                   &lt;attribute name="WIDTH" type="{http://www.opentrafficsim.org/ots}LENGTHTYPE" />
 *                   &lt;attribute name="COLOR" type="{http://www.opentrafficsim.org/ots}COLORTYPE" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ROADTYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="WIDTH" type="{http://www.opentrafficsim.org/ots}LENGTHTYPE" />
 *       &lt;attribute name="LANEKEEPING" type="{http://www.opentrafficsim.org/ots}LANEKEEPINGTYPE" />
 *       &lt;attribute name="OVERTAKING" type="{http://www.opentrafficsim.org/ots}OVERTAKINGTYPE" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"speedlimit", "laneOrNOTRAFFICLANEOrSHOULDER"})
@XmlRootElement(name = "ROADLAYOUT")
public class ROADLAYOUT
{

    @XmlElement(name = "SPEEDLIMIT")
    protected List<ROADLAYOUT.SPEEDLIMIT> speedlimit;

    @XmlElements({@XmlElement(name = "LANE", type = ROADLAYOUT.LANE.class),
            @XmlElement(name = "NOTRAFFICLANE", type = ROADLAYOUT.NOTRAFFICLANE.class),
            @XmlElement(name = "SHOULDER", type = ROADLAYOUT.SHOULDER.class),
            @XmlElement(name = "STRIPE", type = ROADLAYOUT.STRIPE.class)})
    protected List<Object> laneOrNOTRAFFICLANEOrSHOULDER;

    @XmlAttribute(name = "NAME", required = true)
    protected String name;

    @XmlAttribute(name = "ROADTYPE", required = true)
    protected String roadtype;

    @XmlAttribute(name = "WIDTH")
    protected String width;

    @XmlAttribute(name = "LANEKEEPING")
    protected String lanekeeping;

    @XmlAttribute(name = "OVERTAKING")
    protected String overtaking;

    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;

    /**
     * Gets the value of the speedlimit property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * speedlimit property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSPEEDLIMIT().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ROADLAYOUT.SPEEDLIMIT }
     */
    public List<ROADLAYOUT.SPEEDLIMIT> getSPEEDLIMIT()
    {
        if (speedlimit == null)
        {
            speedlimit = new ArrayList<ROADLAYOUT.SPEEDLIMIT>();
        }
        return this.speedlimit;
    }

    /**
     * Gets the value of the laneOrNOTRAFFICLANEOrSHOULDER property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * laneOrNOTRAFFICLANEOrSHOULDER property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getLANEOrNOTRAFFICLANEOrSHOULDER().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ROADLAYOUT.LANE } {@link ROADLAYOUT.NOTRAFFICLANE }
     * {@link ROADLAYOUT.SHOULDER } {@link ROADLAYOUT.STRIPE }
     */
    public List<Object> getLANEOrNOTRAFFICLANEOrSHOULDER()
    {
        if (laneOrNOTRAFFICLANEOrSHOULDER == null)
        {
            laneOrNOTRAFFICLANEOrSHOULDER = new ArrayList<Object>();
        }
        return this.laneOrNOTRAFFICLANEOrSHOULDER;
    }

    /**
     * Gets the value of the name property.
     * @return possible object is {@link String }
     */
    public String getNAME()
    {
        return name;
    }

    /**
     * Sets the value of the name property.
     * @param value String; allowed object is {@link String }
     */
    public void setNAME(String value)
    {
        this.name = value;
    }

    /**
     * Gets the value of the roadtype property.
     * @return possible object is {@link String }
     */
    public String getROADTYPE()
    {
        return roadtype;
    }

    /**
     * Sets the value of the roadtype property.
     * @param value String; allowed object is {@link String }
     */
    public void setROADTYPE(String value)
    {
        this.roadtype = value;
    }

    /**
     * Gets the value of the width property.
     * @return possible object is {@link String }
     */
    public String getWIDTH()
    {
        return width;
    }

    /**
     * Sets the value of the width property.
     * @param value String; allowed object is {@link String }
     */
    public void setWIDTH(String value)
    {
        this.width = value;
    }

    /**
     * Gets the value of the lanekeeping property.
     * @return possible object is {@link String }
     */
    public String getLANEKEEPING()
    {
        return lanekeeping;
    }

    /**
     * Sets the value of the lanekeeping property.
     * @param value String; allowed object is {@link String }
     */
    public void setLANEKEEPING(String value)
    {
        this.lanekeeping = value;
    }

    /**
     * Gets the value of the overtaking property.
     * @return possible object is {@link String }
     */
    public String getOVERTAKING()
    {
        return overtaking;
    }

    /**
     * Sets the value of the overtaking property.
     * @param value String; allowed object is {@link String }
     */
    public void setOVERTAKING(String value)
    {
        this.overtaking = value;
    }

    /**
     * Gets the value of the base property.
     * @return possible object is {@link String }
     */
    public String getBase()
    {
        return base;
    }

    /**
     * Sets the value of the base property.
     * @param value String; allowed object is {@link String }
     */
    public void setBase(String value)
    {
        this.base = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="SPEEDLIMIT" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="GTUTYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="LEGALSPEEDLIMIT" type="{http://www.opentrafficsim.org/ots}SPEEDTYPE" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="LANETYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OFFSET" use="required" type="{http://www.opentrafficsim.org/ots}SIGNEDLENGTHTYPE" />
     *       &lt;attribute name="WIDTH" type="{http://www.opentrafficsim.org/ots}LENGTHTYPE" />
     *       &lt;attribute name="DIRECTION" use="required" type="{http://www.opentrafficsim.org/ots}DIRECTIONTYPE" />
     *       &lt;attribute name="COLOR" type="{http://www.opentrafficsim.org/ots}COLORTYPE" />
     *       &lt;attribute name="OVERTAKING" type="{http://www.opentrafficsim.org/ots}OVERTAKINGTYPE" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"speedlimit"})
    public static class LANE
    {

        @XmlElement(name = "SPEEDLIMIT")
        protected List<ROADLAYOUT.LANE.SPEEDLIMIT> speedlimit;

        @XmlAttribute(name = "NAME", required = true)
        protected String name;

        @XmlAttribute(name = "LANETYPE")
        protected String lanetype;

        @XmlAttribute(name = "OFFSET", required = true)
        protected String offset;

        @XmlAttribute(name = "WIDTH")
        protected String width;

        @XmlAttribute(name = "DIRECTION", required = true)
        protected String direction;

        @XmlAttribute(name = "COLOR")
        protected String color;

        @XmlAttribute(name = "OVERTAKING")
        protected String overtaking;

        /**
         * Gets the value of the speedlimit property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
         * speedlimit property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getSPEEDLIMIT().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link ROADLAYOUT.LANE.SPEEDLIMIT }
         */
        public List<ROADLAYOUT.LANE.SPEEDLIMIT> getSPEEDLIMIT()
        {
            if (speedlimit == null)
            {
                speedlimit = new ArrayList<ROADLAYOUT.LANE.SPEEDLIMIT>();
            }
            return this.speedlimit;
        }

        /**
         * Gets the value of the name property.
         * @return possible object is {@link String }
         */
        public String getNAME()
        {
            return name;
        }

        /**
         * Sets the value of the name property.
         * @param value String; allowed object is {@link String }
         */
        public void setNAME(String value)
        {
            this.name = value;
        }

        /**
         * Gets the value of the lanetype property.
         * @return possible object is {@link String }
         */
        public String getLANETYPE()
        {
            return lanetype;
        }

        /**
         * Sets the value of the lanetype property.
         * @param value String; allowed object is {@link String }
         */
        public void setLANETYPE(String value)
        {
            this.lanetype = value;
        }

        /**
         * Gets the value of the offset property.
         * @return possible object is {@link String }
         */
        public String getOFFSET()
        {
            return offset;
        }

        /**
         * Sets the value of the offset property.
         * @param value String; allowed object is {@link String }
         */
        public void setOFFSET(String value)
        {
            this.offset = value;
        }

        /**
         * Gets the value of the width property.
         * @return possible object is {@link String }
         */
        public String getWIDTH()
        {
            return width;
        }

        /**
         * Sets the value of the width property.
         * @param value String; allowed object is {@link String }
         */
        public void setWIDTH(String value)
        {
            this.width = value;
        }

        /**
         * Gets the value of the direction property.
         * @return possible object is {@link String }
         */
        public String getDIRECTION()
        {
            return direction;
        }

        /**
         * Sets the value of the direction property.
         * @param value String; allowed object is {@link String }
         */
        public void setDIRECTION(String value)
        {
            this.direction = value;
        }

        /**
         * Gets the value of the color property.
         * @return possible object is {@link String }
         */
        public String getCOLOR()
        {
            return color;
        }

        /**
         * Sets the value of the color property.
         * @param value String; allowed object is {@link String }
         */
        public void setCOLOR(String value)
        {
            this.color = value;
        }

        /**
         * Gets the value of the overtaking property.
         * @return possible object is {@link String }
         */
        public String getOVERTAKING()
        {
            return overtaking;
        }

        /**
         * Sets the value of the overtaking property.
         * @param value String; allowed object is {@link String }
         */
        public void setOVERTAKING(String value)
        {
            this.overtaking = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="GTUTYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="LEGALSPEEDLIMIT" type="{http://www.opentrafficsim.org/ots}SPEEDTYPE" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SPEEDLIMIT
        {

            @XmlAttribute(name = "GTUTYPE", required = true)
            protected String gtutype;

            @XmlAttribute(name = "LEGALSPEEDLIMIT")
            protected String legalspeedlimit;

            /**
             * Gets the value of the gtutype property.
             * @return possible object is {@link String }
             */
            public String getGTUTYPE()
            {
                return gtutype;
            }

            /**
             * Sets the value of the gtutype property.
             * @param value String; allowed object is {@link String }
             */
            public void setGTUTYPE(String value)
            {
                this.gtutype = value;
            }

            /**
             * Gets the value of the legalspeedlimit property.
             * @return possible object is {@link String }
             */
            public String getLEGALSPEEDLIMIT()
            {
                return legalspeedlimit;
            }

            /**
             * Sets the value of the legalspeedlimit property.
             * @param value String; allowed object is {@link String }
             */
            public void setLEGALSPEEDLIMIT(String value)
            {
                this.legalspeedlimit = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OFFSET" use="required" type="{http://www.opentrafficsim.org/ots}SIGNEDLENGTHTYPE" />
     *       &lt;attribute name="WIDTH" type="{http://www.opentrafficsim.org/ots}LENGTHTYPE" />
     *       &lt;attribute name="COLOR" type="{http://www.opentrafficsim.org/ots}COLORTYPE" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NOTRAFFICLANE
    {

        @XmlAttribute(name = "NAME")
        protected String name;

        @XmlAttribute(name = "OFFSET", required = true)
        protected String offset;

        @XmlAttribute(name = "WIDTH")
        protected String width;

        @XmlAttribute(name = "COLOR")
        protected String color;

        /**
         * Gets the value of the name property.
         * @return possible object is {@link String }
         */
        public String getNAME()
        {
            return name;
        }

        /**
         * Sets the value of the name property.
         * @param value String; allowed object is {@link String }
         */
        public void setNAME(String value)
        {
            this.name = value;
        }

        /**
         * Gets the value of the offset property.
         * @return possible object is {@link String }
         */
        public String getOFFSET()
        {
            return offset;
        }

        /**
         * Sets the value of the offset property.
         * @param value String; allowed object is {@link String }
         */
        public void setOFFSET(String value)
        {
            this.offset = value;
        }

        /**
         * Gets the value of the width property.
         * @return possible object is {@link String }
         */
        public String getWIDTH()
        {
            return width;
        }

        /**
         * Sets the value of the width property.
         * @param value String; allowed object is {@link String }
         */
        public void setWIDTH(String value)
        {
            this.width = value;
        }

        /**
         * Gets the value of the color property.
         * @return possible object is {@link String }
         */
        public String getCOLOR()
        {
            return color;
        }

        /**
         * Sets the value of the color property.
         * @param value String; allowed object is {@link String }
         */
        public void setCOLOR(String value)
        {
            this.color = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OFFSET" use="required" type="{http://www.opentrafficsim.org/ots}SIGNEDLENGTHTYPE" />
     *       &lt;attribute name="WIDTH" type="{http://www.opentrafficsim.org/ots}LENGTHTYPE" />
     *       &lt;attribute name="COLOR" type="{http://www.opentrafficsim.org/ots}COLORTYPE" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SHOULDER
    {

        @XmlAttribute(name = "NAME")
        protected String name;

        @XmlAttribute(name = "OFFSET", required = true)
        protected String offset;

        @XmlAttribute(name = "WIDTH")
        protected String width;

        @XmlAttribute(name = "COLOR")
        protected String color;

        /**
         * Gets the value of the name property.
         * @return possible object is {@link String }
         */
        public String getNAME()
        {
            return name;
        }

        /**
         * Sets the value of the name property.
         * @param value String; allowed object is {@link String }
         */
        public void setNAME(String value)
        {
            this.name = value;
        }

        /**
         * Gets the value of the offset property.
         * @return possible object is {@link String }
         */
        public String getOFFSET()
        {
            return offset;
        }

        /**
         * Sets the value of the offset property.
         * @param value String; allowed object is {@link String }
         */
        public void setOFFSET(String value)
        {
            this.offset = value;
        }

        /**
         * Gets the value of the width property.
         * @return possible object is {@link String }
         */
        public String getWIDTH()
        {
            return width;
        }

        /**
         * Sets the value of the width property.
         * @param value String; allowed object is {@link String }
         */
        public void setWIDTH(String value)
        {
            this.width = value;
        }

        /**
         * Gets the value of the color property.
         * @return possible object is {@link String }
         */
        public String getCOLOR()
        {
            return color;
        }

        /**
         * Sets the value of the color property.
         * @param value String; allowed object is {@link String }
         */
        public void setCOLOR(String value)
        {
            this.color = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="GTUTYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="LEGALSPEEDLIMIT" type="{http://www.opentrafficsim.org/ots}SPEEDTYPE" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SPEEDLIMIT
    {

        @XmlAttribute(name = "GTUTYPE", required = true)
        protected String gtutype;

        @XmlAttribute(name = "LEGALSPEEDLIMIT")
        protected String legalspeedlimit;

        /**
         * Gets the value of the gtutype property.
         * @return possible object is {@link String }
         */
        public String getGTUTYPE()
        {
            return gtutype;
        }

        /**
         * Sets the value of the gtutype property.
         * @param value String; allowed object is {@link String }
         */
        public void setGTUTYPE(String value)
        {
            this.gtutype = value;
        }

        /**
         * Gets the value of the legalspeedlimit property.
         * @return possible object is {@link String }
         */
        public String getLEGALSPEEDLIMIT()
        {
            return legalspeedlimit;
        }

        /**
         * Sets the value of the legalspeedlimit property.
         * @param value String; allowed object is {@link String }
         */
        public void setLEGALSPEEDLIMIT(String value)
        {
            this.legalspeedlimit = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TYPE" use="required" type="{http://www.opentrafficsim.org/ots}STRIPETYPE" />
     *       &lt;attribute name="OFFSET" use="required" type="{http://www.opentrafficsim.org/ots}SIGNEDLENGTHTYPE" />
     *       &lt;attribute name="WIDTH" type="{http://www.opentrafficsim.org/ots}LENGTHTYPE" />
     *       &lt;attribute name="COLOR" type="{http://www.opentrafficsim.org/ots}COLORTYPE" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class STRIPE
    {

        @XmlAttribute(name = "NAME")
        protected String name;

        @XmlAttribute(name = "TYPE", required = true)
        protected String type;

        @XmlAttribute(name = "OFFSET", required = true)
        protected String offset;

        @XmlAttribute(name = "WIDTH")
        protected String width;

        @XmlAttribute(name = "COLOR")
        protected String color;

        /**
         * Gets the value of the name property.
         * @return possible object is {@link String }
         */
        public String getNAME()
        {
            return name;
        }

        /**
         * Sets the value of the name property.
         * @param value String; allowed object is {@link String }
         */
        public void setNAME(String value)
        {
            this.name = value;
        }

        /**
         * Gets the value of the type property.
         * @return possible object is {@link String }
         */
        public String getTYPE()
        {
            return type;
        }

        /**
         * Sets the value of the type property.
         * @param value String; allowed object is {@link String }
         */
        public void setTYPE(String value)
        {
            this.type = value;
        }

        /**
         * Gets the value of the offset property.
         * @return possible object is {@link String }
         */
        public String getOFFSET()
        {
            return offset;
        }

        /**
         * Sets the value of the offset property.
         * @param value String; allowed object is {@link String }
         */
        public void setOFFSET(String value)
        {
            this.offset = value;
        }

        /**
         * Gets the value of the width property.
         * @return possible object is {@link String }
         */
        public String getWIDTH()
        {
            return width;
        }

        /**
         * Sets the value of the width property.
         * @param value String; allowed object is {@link String }
         */
        public void setWIDTH(String value)
        {
            this.width = value;
        }

        /**
         * Gets the value of the color property.
         * @return possible object is {@link String }
         */
        public String getCOLOR()
        {
            return color;
        }

        /**
         * Sets the value of the color property.
         * @param value String; allowed object is {@link String }
         */
        public void setCOLOR(String value)
        {
            this.color = value;
        }

    }

}
