package org.opentrafficsim.core.value.vfloat.vector;

import org.opentrafficsim.core.unit.SICoefficients;
import org.opentrafficsim.core.unit.SIUnit;
import org.opentrafficsim.core.unit.Unit;
import org.opentrafficsim.core.value.Absolute;
import org.opentrafficsim.core.value.DenseData;
import org.opentrafficsim.core.value.Relative;
import org.opentrafficsim.core.value.SparseData;
import org.opentrafficsim.core.value.ValueException;
import org.opentrafficsim.core.value.vfloat.FloatMathFunctions;
import org.opentrafficsim.core.value.vfloat.FloatMathFunctionsImpl;
import org.opentrafficsim.core.value.vfloat.scalar.FloatScalar;

import cern.colt.matrix.tfloat.FloatMatrix1D;
import cern.colt.matrix.tfloat.impl.DenseFloatMatrix1D;
import cern.colt.matrix.tfloat.impl.SparseFloatMatrix1D;
import cern.jet.math.tfloat.FloatFunctions;

/**
 * MutableFloatVector.
 * <p>
 * This file was generated by the OpenTrafficSim valueclasses generator, 05 okt, 2014
 * <p>
 * Copyright (c) 2014 Delft University of Technology, PO Box 5, 2600 AA, Delft, the Netherlands. All rights reserved. <br>
 * BSD-style license. See <a href="http://opentrafficsim.org/node/13">OpenTrafficSim License</a>.
 * <p>
 * @version 05 okt, 2014 <br>
 * @author <a href="http://www.tbm.tudelft.nl/averbraeck">Alexander Verbraeck</a>
 * @author <a href="http://www.tudelft.nl/pknoppers">Peter Knoppers</a>
 * @param <U> Unit; the unit of this MutableFloatVector
 */
public abstract class MutableFloatVector<U extends Unit<U>> extends FloatVector<U> implements 
        WriteFloatVectorFunctions<U>, FloatMathFunctions
{
    /**  */
    private static final long serialVersionUID = 20141005L;

    /**
     * Construct a new MutableFloatVector.
     * @param unit U; the unit of the new MutableFloatVector
     */
    protected MutableFloatVector(final U unit)
    {
        super(unit);
        // System.out.println("Created MutableFloatVector");
    }

    /** If set, any modification of the data must be preceded by replacing the data with a local copy. */
    private boolean copyOnWrite = false;

    /**
     * Retrieve the value of the copyOnWrite flag.
     * @return boolean
     */
    private boolean isCopyOnWrite()
    {
        return this.copyOnWrite;
    }

    /**
     * Change the copyOnWrite flag.
     * @param copyOnWrite boolean; the new value for the copyOnWrite flag
     */
    final void setCopyOnWrite(final boolean copyOnWrite)
    {
        this.copyOnWrite = copyOnWrite;
    }

    /** {@inheritDoc} */
    @Override
    public final void normalize() throws ValueException
    {
        float sum = zSum();
        if (0 == sum)
        {
            throw new ValueException("zSum is 0; cannot normalize");
        }
        checkCopyOnWrite();
        for (int i = 0; i < size(); i++)
        {
            safeSet(i, safeGet(i) / sum);
        }
    }

    /**
     * @param <U> Unit
     */
    public abstract static class Abs<U extends Unit<U>> extends MutableFloatVector<U> implements Absolute
    {
        /**  */
        private static final long serialVersionUID = 20141005L;

        /**
         * Construct a new Absolute MutableFloatVector.
         * @param unit U; the unit of the new Absolute MutableFloatVector
         */
        protected Abs(final U unit)
        {
            super(unit);
            // System.out.println("Created Abs");
        }

        /**
         * @param <U> Unit
         */
        public static class Dense<U extends Unit<U>> extends Abs<U> implements DenseData
        {
            /**  */
            private static final long serialVersionUID = 20141005L;

            /**
             * Construct a new Absolute Dense MutableFloatVector.
             * @param values float[]; the initial values of the entries in the new Absolute Dense MutableFloatVector
             * @param unit U; the unit of the new Absolute Dense MutableFloatVector
             */
            public Dense(final float[] values, final U unit)
            {
                super(unit);
                // System.out.println("Created Dense");
                initialize(values);
            }

            /**
             * Construct a new Absolute Dense MutableFloatVector.
             * @param values FloatScalar.Abs&lt;U&gt;[]; the initial values of the entries in the new Absolute Dense
             *            MutableFloatVector
             * @throws ValueException when values has zero entries
             */
            public Dense(final FloatScalar.Abs<U>[] values) throws ValueException
            {
                super(checkNonEmpty(values)[0].getUnit());
                // System.out.println("Created Dense");
                initialize(values);
            }

            /**
             * For package internal use only.
             * @param values FloatMatrix1D; the initial values of the entries in the new Absolute Dense
             *            MutableFloatVector
             * @param unit U; the unit of the new Absolute Dense MutableFloatVector
             */
            protected Dense(final FloatMatrix1D values, final U unit)
            {
                super(unit);
                // System.out.println("Created Dense");
                setCopyOnWrite(true);
                initialize(values); // shallow copy
            }

            /** {@inheritDoc} */
            @Override
            public final FloatVector.Abs.Dense<U> immutable()
            {
                setCopyOnWrite(true);
                return new FloatVector.Abs.Dense<U>(getVectorSI(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            public final MutableFloatVector.Abs.Dense<U> mutable()
            {
                setCopyOnWrite(true);
                return new MutableFloatVector.Abs.Dense<U>(getVectorSI(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            protected final FloatMatrix1D createMatrix1D(final int size)
            {
                return new DenseFloatMatrix1D(size);
            }

        }

        /**
         * @param <U> Unit
         */
        public static class Sparse<U extends Unit<U>> extends Abs<U> implements SparseData
        {
            /**  */
            private static final long serialVersionUID = 20141005L;

            /**
             * Construct a new Absolute Sparse MutableFloatVector.
             * @param values float[]; the initial values of the entries in the new Absolute Sparse MutableFloatVector
             * @param unit U; the unit of the new Absolute Sparse MutableFloatVector
             */
            public Sparse(final float[] values, final U unit)
            {
                super(unit);
                // System.out.println("Created Sparse");
                initialize(values);
            }

            /**
             * Construct a new Absolute Sparse MutableFloatVector.
             * @param values FloatScalar.Abs&lt;U&gt;[]; the initial values of the entries in the new Absolute Sparse
             *            MutableFloatVector
             * @throws ValueException when values has zero entries
             */
            public Sparse(final FloatScalar.Abs<U>[] values) throws ValueException
            {
                super(checkNonEmpty(values)[0].getUnit());
                // System.out.println("Created Sparse");
                initialize(values);
            }

            /**
             * For package internal use only.
             * @param values FloatMatrix1D; the initial values of the entries in the new Absolute Sparse
             *            MutableFloatVector
             * @param unit U; the unit of the new Absolute Sparse MutableFloatVector
             */
            protected Sparse(final FloatMatrix1D values, final U unit)
            {
                super(unit);
                // System.out.println("Created Sparse");
                setCopyOnWrite(true);
                initialize(values); // shallow copy
            }

            /** {@inheritDoc} */
            @Override
            public final FloatVector.Abs.Sparse<U> immutable()
            {
                setCopyOnWrite(true);
                return new FloatVector.Abs.Sparse<U>(getVectorSI(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            public final MutableFloatVector.Abs.Sparse<U> mutable()
            {
                setCopyOnWrite(true);
                return new MutableFloatVector.Abs.Sparse<U>(getVectorSI(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            protected final FloatMatrix1D createMatrix1D(final int size)
            {
                return new SparseFloatMatrix1D(size);
            }

        }

        /** {@inheritDoc} */
        @Override
        public final FloatScalar.Abs<U> get(final int index) throws ValueException
        {
            return new FloatScalar.Abs<U>(getInUnit(index, getUnit()), getUnit());
        }

    }

    /**
     * @param <U> Unit
     */
    public abstract static class Rel<U extends Unit<U>> extends MutableFloatVector<U> implements Relative
    {
        /**  */
        private static final long serialVersionUID = 20141005L;

        /**
         * Construct a new Relative MutableFloatVector.
         * @param unit U; the unit of the new Relative MutableFloatVector
         */
        protected Rel(final U unit)
        {
            super(unit);
            // System.out.println("Created Rel");
        }

        /**
         * @param <U> Unit
         */
        public static class Dense<U extends Unit<U>> extends Rel<U> implements DenseData
        {
            /**  */
            private static final long serialVersionUID = 20141005L;

            /**
             * Construct a new Relative Dense MutableFloatVector.
             * @param values float[]; the initial values of the entries in the new Relative Dense MutableFloatVector
             * @param unit U; the unit of the new Relative Dense MutableFloatVector
             */
            public Dense(final float[] values, final U unit)
            {
                super(unit);
                // System.out.println("Created Dense");
                initialize(values);
            }

            /**
             * Construct a new Relative Dense MutableFloatVector.
             * @param values FloatScalar.Rel&lt;U&gt;[]; the initial values of the entries in the new Relative Dense
             *            MutableFloatVector
             * @throws ValueException when values has zero entries
             */
            public Dense(final FloatScalar.Rel<U>[] values) throws ValueException
            {
                super(checkNonEmpty(values)[0].getUnit());
                // System.out.println("Created Dense");
                initialize(values);
            }

            /**
             * For package internal use only.
             * @param values FloatMatrix1D; the initial values of the entries in the new Relative Dense
             *            MutableFloatVector
             * @param unit U; the unit of the new Relative Dense MutableFloatVector
             */
            protected Dense(final FloatMatrix1D values, final U unit)
            {
                super(unit);
                // System.out.println("Created Dense");
                setCopyOnWrite(true);
                initialize(values); // shallow copy
            }

            /** {@inheritDoc} */
            @Override
            public final FloatVector.Rel.Dense<U> immutable()
            {
                setCopyOnWrite(true);
                return new FloatVector.Rel.Dense<U>(getVectorSI(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            public final MutableFloatVector.Rel.Dense<U> mutable()
            {
                setCopyOnWrite(true);
                return new MutableFloatVector.Rel.Dense<U>(getVectorSI(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            protected final FloatMatrix1D createMatrix1D(final int size)
            {
                return new DenseFloatMatrix1D(size);
            }

        }

        /**
         * @param <U> Unit
         */
        public static class Sparse<U extends Unit<U>> extends Rel<U> implements SparseData
        {
            /**  */
            private static final long serialVersionUID = 20141005L;

            /**
             * Construct a new Relative Sparse MutableFloatVector.
             * @param values float[]; the initial values of the entries in the new Relative Sparse MutableFloatVector
             * @param unit U; the unit of the new Relative Sparse MutableFloatVector
             */
            public Sparse(final float[] values, final U unit)
            {
                super(unit);
                // System.out.println("Created Sparse");
                initialize(values);
            }

            /**
             * Construct a new Relative Sparse MutableFloatVector.
             * @param values FloatScalar.Rel&lt;U&gt;[]; the initial values of the entries in the new Relative Sparse
             *            MutableFloatVector
             * @throws ValueException when values has zero entries
             */
            public Sparse(final FloatScalar.Rel<U>[] values) throws ValueException
            {
                super(checkNonEmpty(values)[0].getUnit());
                // System.out.println("Created Sparse");
                initialize(values);
            }

            /**
             * For package internal use only.
             * @param values FloatMatrix1D; the initial values of the entries in the new Relative Sparse
             *            MutableFloatVector
             * @param unit U; the unit of the new Relative Sparse MutableFloatVector
             */
            protected Sparse(final FloatMatrix1D values, final U unit)
            {
                super(unit);
                // System.out.println("Created Sparse");
                setCopyOnWrite(true);
                initialize(values); // shallow copy
            }

            /** {@inheritDoc} */
            @Override
            public final FloatVector.Rel.Sparse<U> immutable()
            {
                setCopyOnWrite(true);
                return new FloatVector.Rel.Sparse<U>(getVectorSI(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            public final MutableFloatVector.Rel.Sparse<U> mutable()
            {
                setCopyOnWrite(true);
                return new MutableFloatVector.Rel.Sparse<U>(getVectorSI(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            protected final FloatMatrix1D createMatrix1D(final int size)
            {
                return new SparseFloatMatrix1D(size);
            }

        }

        /** {@inheritDoc} */
        @Override
        public final FloatScalar.Rel<U> get(final int index) throws ValueException
        {
            return new FloatScalar.Rel<U>(getInUnit(index, getUnit()), getUnit());
        }

    }

    /**
     * Make (immutable) FloatVector equivalent for any type of MutableFloatVector.
     * @return FloatVector&lt;U&gt;
     */
    public abstract FloatVector<U> immutable();

    /** {@inheritDoc} */
    @Override
    public final MutableFloatVector<U> copy()
    {
        return immutable().mutable();
        // FIXME: This may cause both the original and the copy to be deep copied later
        // Maybe it is better to make one deep copy now...
    }

    /**
     * Check the copyOnWrite flag and, if it is set, make a deep copy of the data and clear the flag.
     */
    protected final void checkCopyOnWrite()
    {
        if (isCopyOnWrite())
        {
            // System.out.println("copyOnWrite is set: Copying data");
            deepCopyData();
            setCopyOnWrite(false);
        }
    }

    /** {@inheritDoc} */
    @Override
    public final void setSI(final int index, final float valueSI) throws ValueException
    {
        checkIndex(index);
        checkCopyOnWrite();
        safeSet(index, valueSI);
    }

    /** {@inheritDoc} */
    @Override
    public final void set(final int index, final FloatScalar<U> value) throws ValueException
    {
        setSI(index, value.getValueSI());
    }

    /** {@inheritDoc} */
    @Override
    public final void setInUnit(final int index, final float value, final U valueUnit) throws ValueException
    {
        // TODO: creating a FloatScalar.Abs along the way may not be the most efficient way to do this...
        setSI(index, new FloatScalar.Abs<U>(value, valueUnit).getValueSI());
    }

    /**
     * Execute a function on a cell by cell basis.
     * @param f cern.colt.function.tfloat.FloatFunction; the function to apply
     */
    public final void assign(final cern.colt.function.tfloat.FloatFunction f)
    {
        checkCopyOnWrite();
        getVectorSI().assign(f);
    }

    /** {@inheritDoc} */
    @Override
    public final void abs()
    {
        assign(FloatFunctions.abs);
    }

    /** {@inheritDoc} */
    @Override
    public final void acos()
    {
        assign(FloatFunctions.acos);
    }

    /** {@inheritDoc} */
    @Override
    public final void asin()
    {
        assign(FloatFunctions.asin);
    }

    /** {@inheritDoc} */
    @Override
    public final void atan()
    {
        assign(FloatFunctions.atan);
    }

    /** {@inheritDoc} */
    @Override
    public final void cbrt()
    {
        assign(FloatMathFunctionsImpl.cbrt);
    }

    /** {@inheritDoc} */
    @Override
    public final void ceil()
    {
        assign(FloatFunctions.ceil);
    }

    /** {@inheritDoc} */
    @Override
    public final void cos()
    {
        assign(FloatFunctions.cos);
    }

    /** {@inheritDoc} */
    @Override
    public final void cosh()
    {
        assign(FloatMathFunctionsImpl.cosh);
    }

    /** {@inheritDoc} */
    @Override
    public final void exp()
    {
        assign(FloatFunctions.exp);
    }

    /** {@inheritDoc} */
    @Override
    public final void expm1()
    {
        assign(FloatMathFunctionsImpl.expm1);
    }

    /** {@inheritDoc} */
    @Override
    public final void floor()
    {
        assign(FloatFunctions.floor);
    }

    /** {@inheritDoc} */
    @Override
    public final void log()
    {
        assign(FloatFunctions.log);
    }

    /** {@inheritDoc} */
    @Override
    public final void log10()
    {
        assign(FloatMathFunctionsImpl.log10);
    }

    /** {@inheritDoc} */
    @Override
    public final void log1p()
    {
        assign(FloatMathFunctionsImpl.log1p);
    }

    /** {@inheritDoc} */
    @Override
    public final void pow(final double x)
    {
        assign(FloatFunctions.pow((float) x));
    }

    /** {@inheritDoc} */
    @Override
    public final void rint()
    {
        assign(FloatFunctions.rint);
    }

    /** {@inheritDoc} */
    @Override
    public final void round()
    {
        assign(FloatMathFunctionsImpl.round);
    }

    /** {@inheritDoc} */
    @Override
    public final void signum()
    {
        assign(FloatMathFunctionsImpl.signum);
    }

    /** {@inheritDoc} */
    @Override
    public final void sin()
    {
        assign(FloatFunctions.sin);
    }

    /** {@inheritDoc} */
    @Override
    public final void sinh()
    {
        assign(FloatMathFunctionsImpl.sinh);
    }

    /** {@inheritDoc} */
    @Override
    public final void sqrt()
    {
        assign(FloatFunctions.sqrt);
    }

    /** {@inheritDoc} */
    @Override
    public final void tan()
    {
        assign(FloatFunctions.tan);
    }

    /** {@inheritDoc} */
    @Override
    public final void tanh()
    {
        assign(FloatMathFunctionsImpl.tanh);
    }

    /** {@inheritDoc} */
    @Override
    public final void toDegrees()
    {
        assign(FloatMathFunctionsImpl.toDegrees);
    }

    /** {@inheritDoc} */
    @Override
    public final void toRadians()
    {
        assign(FloatMathFunctionsImpl.toRadians);
    }

    /** {@inheritDoc} */
    @Override
    public final void inv()
    {
        assign(FloatFunctions.inv);
    }

    /** {@inheritDoc} */
    @Override
    public final void multiply(final float constant)
    {
        assign(FloatFunctions.mult(constant));
    }

    /** {@inheritDoc} */
    @Override
    public final void divide(final float constant)
    {
        assign(FloatFunctions.div(constant));
    }

    /**
     * Increment the values in this MutableFloatVector by the corresponding values in a FloatVector.
     * @param increment FloatVector&lt;U&gt;; the values by which to increment the corresponding values in this
     *            MutableFloatVector
     * @return MutableFloatVector&lt;U&gt;; this modified MutableFloatVector
     * @throws ValueException when the vectors do not have the same size
     */
    private MutableFloatVector<U> incrementValueByValue(final FloatVector<U> increment) throws ValueException
    {
        checkSizeAndCopyOnWrite(increment);
        for (int index = size(); --index >= 0;)
        {
            safeSet(index, safeGet(index) + increment.safeGet(index));
        }
        return this;
    }

    /**
     * Increment the values in this MutableFloatVector by the corresponding values in a Relative FloatVector.
     * @param rel FloatVector.Rel&lt;U&gt;; the Relative FloatVector
     * @return MutableFloatVector&lt;U&gt;; this modified MutableFloatVector
     * @throws ValueException when the vectors do not have the same size
     */
    public final MutableFloatVector<U> incrementBy(final FloatVector.Rel<U> rel) throws ValueException
    {
        return incrementValueByValue(rel);
    }

    /**
     * Decrement the values in this MutableFloatVector by the corresponding values in a FloatVector.
     * @param decrement FloatVector&lt;U&gt;; the values by which to decrement the corresponding values in this
     *            MutableFloatVector
     * @return MutableFloatVector&lt;U&gt;; this modified MutableFloatVector
     * @throws ValueException when the vectors do not have the same size
     */
    private MutableFloatVector<U> decrementValueByValue(final FloatVector<U> decrement) throws ValueException
    {
        checkSizeAndCopyOnWrite(decrement);
        for (int index = size(); --index >= 0;)
        {
            safeSet(index, safeGet(index) - decrement.safeGet(index));
        }
        return this;
    }

    /**
     * Decrement the values in this MutableFloatVector by the corresponding values in a Relative FloatVector.
     * @param rel FloatVector.Rel&lt;U&gt;; the Relative FloatVector
     * @return MutableFloatVector&lt;U&gt;; this modified MutableFloatVector
     * @throws ValueException when the vectors do not have the same size
     */
    public final MutableFloatVector<U> decrementBy(final FloatVector.Rel<U> rel) throws ValueException
    {
        return decrementValueByValue(rel);
    }

    /**
     * Decrement the values in this Relative MutableFloatVector by the corresponding values in an Absolute FloatVector.
     * @param abs FloatVector.Abs&lt;U&gt;; the Absolute FloatVector
     * @return MutableFloatVector.Rel&lt;U&gt;; this modified Relative MutableFloatVector
     * @throws ValueException when the vectors do not have the same size
     */
    protected final MutableFloatVector.Rel<U> decrementBy(final FloatVector.Abs<U> abs) throws ValueException
    {
        return (MutableFloatVector.Rel<U>) decrementValueByValue(abs);
    }

    /**
     * Scale the values in this MutableFloatVector by the corresponding values in a FloatVector.
     * @param factor FloatVector&lt;?&gt;; contains the values by which to scale the corresponding values in this
     *            MutableFloatVector
     * @throws ValueException when the vectors do not have the same size
     */
    public final void scaleValueByValue(final FloatVector<?> factor) throws ValueException
    {
        checkSizeAndCopyOnWrite(factor);
        for (int index = size(); --index >= 0;)
        {
            safeSet(index, safeGet(index) * factor.safeGet(index));
        }
    }

    /**
     * Scale the values in this MutableFloatVector by the corresponding values in a float array.
     * @param factor float[]; contains the values by which to scale the corresponding values in this MutableFloatVector
     * @return MutableFloatVector&lt;U&gt;; this modified MutableFloatVector
     * @throws ValueException when the vector and the array do not have the same size
     */
    public final MutableFloatVector<U> scaleValueByValue(final float[] factor) throws ValueException
    {
        checkSizeAndCopyOnWrite(factor);
        for (int index = size(); --index >= 0;)
        {
            safeSet(index, safeGet(index) * factor[index]);
        }
        return this;
    }

    /**
     * Check sizes and copy the data if the copyOnWrite flag is set.
     * @param other FloatVector&lt;?&gt;; partner for the size check
     * @throws ValueException when the vectors do not have the same size
     */
    private void checkSizeAndCopyOnWrite(final FloatVector<?> other) throws ValueException
    {
        checkSize(other);
        checkCopyOnWrite();
    }

    /**
     * Check sizes and copy the data if the copyOnWrite flag is set.
     * @param other float[]; partner for the size check
     * @throws ValueException when the vectors do not have the same size
     */
    private void checkSizeAndCopyOnWrite(final float[] other) throws ValueException
    {
        checkSize(other);
        checkCopyOnWrite();
    }

    /**
     * Add two FloatVectors value by value and store the result in a new MutableFloatVector.Abs.Dense&lt;U&gt;.
     * @param left FloatVector.Abs.Dense&lt;U&gt;; the left operand
     * @param right FloatVector.Rel&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Abs.Dense&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Abs.Dense<U> plus(final FloatVector.Abs.Dense<U> left,
            final FloatVector.Rel<U> right) throws ValueException
    {
        return (MutableFloatVector.Abs.Dense<U>) left.mutable().incrementBy(right);
    }

    /**
     * Add two FloatVectors value by value and store the result in a new MutableFloatVector.Abs.Dense&lt;U&gt;.
     * @param left FloatVector.Abs.Sparse&lt;U&gt;; the left operand
     * @param right FloatVector.Rel.Dense&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Abs.Dense&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Abs.Dense<U> plus(final FloatVector.Abs.Sparse<U> left,
            final FloatVector.Rel.Dense<U> right) throws ValueException
    {
        return (MutableFloatVector.Abs.Dense<U>) sparseToDense(left).incrementBy(right);
    }

    /**
     * Add two FloatVectors value by value and store the result in a new MutableFloatVector.Abs.Sparse&lt;U&gt;.
     * @param left FloatVector.Abs.Sparse&lt;U&gt;; the left operand
     * @param right FloatVector.Rel.Sparse&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Abs.Sparse&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Abs.Sparse<U> plus(final FloatVector.Abs.Sparse<U> left,
            final FloatVector.Rel.Sparse<U> right) throws ValueException
    {
        return (MutableFloatVector.Abs.Sparse<U>) left.mutable().incrementBy(right);
    }

    /**
     * Add two FloatVectors value by value and store the result in a new MutableFloatVector.Rel.Dense&lt;U&gt;.
     * @param left FloatVector.Rel.Dense&lt;U&gt;; the left operand
     * @param right FloatVector.Rel&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Rel.Dense&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Dense<U> plus(final FloatVector.Rel.Dense<U> left,
            final FloatVector.Rel<U> right) throws ValueException
    {
        return (MutableFloatVector.Rel.Dense<U>) left.mutable().incrementBy(right);
    }

    /**
     * Add two FloatVectors value by value and store the result in a new MutableFloatVector.Rel.Dense&lt;U&gt;.
     * @param left FloatVector.Rel.Sparse&lt;U&gt;; the left operand
     * @param right FloatVector.Rel.Dense&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Rel.Dense&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Dense<U> plus(final FloatVector.Rel.Sparse<U> left,
            final FloatVector.Rel.Dense<U> right) throws ValueException
    {
        return (MutableFloatVector.Rel.Dense<U>) sparseToDense(left).incrementBy(right);
    }

    /**
     * Add two FloatVectors value by value and store the result in a new MutableFloatVector.Rel.Sparse&lt;U&gt;.
     * @param left FloatVector.Rel.Sparse&lt;U&gt;; the left operand
     * @param right FloatVector.Rel.Sparse&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Rel.Sparse&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Sparse<U> plus(final FloatVector.Rel.Sparse<U> left,
            final FloatVector.Rel.Sparse<U> right) throws ValueException
    {
        return (MutableFloatVector.Rel.Sparse<U>) left.mutable().incrementBy(right);
    }

    /**
     * Subtract two FloatVectors value by value and store the result in a new MutableFloatVector.Rel.Dense&lt;U&gt;.
     * @param left FloatVector.Abs.Dense&lt;U&gt;; the left operand
     * @param right FloatVector.Abs&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Rel.Dense&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Dense<U> minus(final FloatVector.Abs.Dense<U> left,
            final FloatVector.Abs<U> right) throws ValueException
    {
        return (MutableFloatVector.Rel.Dense<U>) new MutableFloatVector.Rel.Dense<U>(left.deepCopyOfData(),
                    left.getUnit()).decrementBy(right);
    }

    /**
     * Subtract two FloatVectors value by value and store the result in a new MutableFloatVector.Rel.Sparse&lt;U&gt;.
     * @param left FloatVector.Abs.Sparse&lt;U&gt;; the left operand
     * @param right FloatVector.Abs.Sparse&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Rel.Sparse&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Sparse<U> minus(final FloatVector.Abs.Sparse<U> left,
            final FloatVector.Abs.Sparse<U> right) throws ValueException
    {
        return (MutableFloatVector.Rel.Sparse<U>) new MutableFloatVector.Rel.Sparse<U>(left.deepCopyOfData(),
                    left.getUnit()).decrementBy(right);
    }

    /**
     * Subtract two FloatVectors value by value and store the result in a new MutableFloatVector.Rel.Dense&lt;U&gt;.
     * @param left FloatVector.Abs.Sparse&lt;U&gt;; the left operand
     * @param right FloatVector.Abs.Dense&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Rel.Dense&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Dense<U> minus(final FloatVector.Abs.Sparse<U> left,
            final FloatVector.Abs.Dense<U> right) throws ValueException
    {
        return (MutableFloatVector.Rel.Dense<U>) new MutableFloatVector.Rel.Dense<U>(left.deepCopyOfData(),
                    left.getUnit()).decrementBy(right);
    }

    /**
     * Subtract two FloatVectors value by value and store the result in a new MutableFloatVector.Abs.Dense&lt;U&gt;.
     * @param left FloatVector.Abs.Dense&lt;U&gt;; the left operand
     * @param right FloatVector.Rel&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Abs.Dense&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Abs.Dense<U> minus(final FloatVector.Abs.Dense<U> left,
            final FloatVector.Rel<U> right) throws ValueException
    {
        return (MutableFloatVector.Abs.Dense<U>) left.mutable().decrementBy(right);
    }

    /**
     * Subtract two FloatVectors value by value and store the result in a new MutableFloatVector.Abs.Dense&lt;U&gt;.
     * @param left FloatVector.Abs.Sparse&lt;U&gt;; the left operand
     * @param right FloatVector.Rel.Dense&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Abs.Dense&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Abs.Dense<U> minus(final FloatVector.Abs.Sparse<U> left,
            final FloatVector.Rel.Dense<U> right) throws ValueException
    {
        return (MutableFloatVector.Abs.Dense<U>) sparseToDense(left).decrementBy(right);
    }

    /**
     * Subtract two FloatVectors value by value and store the result in a new MutableFloatVector.Abs.Sparse&lt;U&gt;.
     * @param left FloatVector.Abs.Sparse&lt;U&gt;; the left operand
     * @param right FloatVector.Rel.Sparse&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Abs.Sparse&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Abs.Sparse<U> minus(final FloatVector.Abs.Sparse<U> left,
            final FloatVector.Rel.Sparse<U> right) throws ValueException
    {
        return (MutableFloatVector.Abs.Sparse<U>) left.mutable().decrementBy(right);
    }

    /**
     * Subtract two FloatVectors value by value and store the result in a new MutableFloatVector.Rel.Dense&lt;U&gt;.
     * @param left FloatVector.Rel.Dense&lt;U&gt;; the left operand
     * @param right FloatVector.Rel&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Rel.Dense&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Dense<U> minus(final FloatVector.Rel.Dense<U> left,
            final FloatVector.Rel<U> right) throws ValueException
    {
        return (MutableFloatVector.Rel.Dense<U>) left.mutable().decrementBy(right);
    }

    /**
     * Subtract two FloatVectors value by value and store the result in a new MutableFloatVector.Rel.Dense&lt;U&gt;.
     * @param left FloatVector.Rel.Sparse&lt;U&gt;; the left operand
     * @param right FloatVector.Rel.Dense&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Rel.Dense&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Dense<U> minus(final FloatVector.Rel.Sparse<U> left,
            final FloatVector.Rel.Dense<U> right) throws ValueException
    {
        return (MutableFloatVector.Rel.Dense<U>) sparseToDense(left).decrementBy(right);
    }

    /**
     * Subtract two FloatVectors value by value and store the result in a new MutableFloatVector.Rel.Sparse&lt;U&gt;.
     * @param left FloatVector.Rel.Sparse&lt;U&gt;; the left operand
     * @param right FloatVector.Rel.Sparse&lt;U&gt;; the right operand
     * @param <U> Unit; the unit of the parameters and the result
     * @return MutableFloatVector.Rel.Sparse&lt;U&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Sparse<U> minus(final FloatVector.Rel.Sparse<U> left,
            final FloatVector.Rel.Sparse<U> right) throws ValueException
    {
        return (MutableFloatVector.Rel.Sparse<U>) left.mutable().decrementBy(right);
    }

    /**
     * Multiply two FloatVectors value by value and store the result in a new
     * MutableFloatVector.Abs.Dense&lt;SIUnit&gt;.
     * @param left FloatVector.Abs.Dense&lt;?&gt;; the left operand
     * @param right FloatVector.Abs.Dense&lt;?&gt;; the right operand
     * @return MutableFloatVector.Abs.Dense&lt;SIUnit&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static MutableFloatVector.Abs.Dense<SIUnit> times(final FloatVector.Abs.Dense<?> left,
            final FloatVector.Abs.Dense<?> right) throws ValueException
    {
        SIUnit targetUnit =
                Unit.lookupOrCreateSIUnitWithSICoefficients(SICoefficients.multiply(left.getUnit().getSICoefficients(),
                        right.getUnit().getSICoefficients()).toString());
        MutableFloatVector.Abs.Dense<SIUnit> work =
                new MutableFloatVector.Abs.Dense<SIUnit>(left.deepCopyOfData(), targetUnit);
        work.scaleValueByValue(right);
        return work;
    }

    /**
     * Multiply two FloatVectors value by value and store the result in a new
     * MutableFloatVector.Abs.Sparse&lt;SIUnit&gt;.
     * @param left FloatVector.Abs.Dense&lt;?&gt;; the left operand
     * @param right FloatVector.Abs.Sparse&lt;?&gt;; the right operand
     * @return MutableFloatVector.Abs.Sparse&lt;SIUnit&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static MutableFloatVector.Abs.Sparse<SIUnit> times(final FloatVector.Abs.Dense<?> left,
            final FloatVector.Abs.Sparse<?> right) throws ValueException
    {
        SIUnit targetUnit =
                Unit.lookupOrCreateSIUnitWithSICoefficients(SICoefficients.multiply(left.getUnit().getSICoefficients(),
                        right.getUnit().getSICoefficients()).toString());
        MutableFloatVector.Abs.Sparse<SIUnit> work =
                new MutableFloatVector.Abs.Sparse<SIUnit>(left.deepCopyOfData(), targetUnit);
        work.scaleValueByValue(right);
        return work;
    }

    /**
     * Multiply two FloatVectors value by value and store the result in a new
     * MutableFloatVector.Abs.Sparse&lt;SIUnit&gt;.
     * @param left FloatVector.Abs.Sparse&lt;?&gt;; the left operand
     * @param right FloatVector.Abs&lt;?&gt;; the right operand
     * @return MutableFloatVector.Abs.Sparse&lt;SIUnit&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static MutableFloatVector.Abs.Sparse<SIUnit> times(final FloatVector.Abs.Sparse<?> left,
            final FloatVector.Abs<?> right) throws ValueException
    {
        SIUnit targetUnit =
                Unit.lookupOrCreateSIUnitWithSICoefficients(SICoefficients.multiply(left.getUnit().getSICoefficients(),
                        right.getUnit().getSICoefficients()).toString());
        MutableFloatVector.Abs.Sparse<SIUnit> work =
                new MutableFloatVector.Abs.Sparse<SIUnit>(left.deepCopyOfData(), targetUnit);
        work.scaleValueByValue(right);
        return work;
    }

    /**
     * Multiply two FloatVectors value by value and store the result in a new
     * MutableFloatVector.Rel.Dense&lt;SIUnit&gt;.
     * @param left FloatVector.Rel.Dense&lt;?&gt;; the left operand
     * @param right FloatVector.Rel.Dense&lt;?&gt;; the right operand
     * @return MutableFloatVector.Rel.Dense&lt;SIUnit&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static MutableFloatVector.Rel.Dense<SIUnit> times(final FloatVector.Rel.Dense<?> left,
            final FloatVector.Rel.Dense<?> right) throws ValueException
    {
        SIUnit targetUnit =
                Unit.lookupOrCreateSIUnitWithSICoefficients(SICoefficients.multiply(left.getUnit().getSICoefficients(),
                        right.getUnit().getSICoefficients()).toString());
        MutableFloatVector.Rel.Dense<SIUnit> work =
                new MutableFloatVector.Rel.Dense<SIUnit>(left.deepCopyOfData(), targetUnit);
        work.scaleValueByValue(right);
        return work;
    }

    /**
     * Multiply two FloatVectors value by value and store the result in a new
     * MutableFloatVector.Rel.Sparse&lt;SIUnit&gt;.
     * @param left FloatVector.Rel.Dense&lt;?&gt;; the left operand
     * @param right FloatVector.Rel.Sparse&lt;?&gt;; the right operand
     * @return MutableFloatVector.Rel.Sparse&lt;SIUnit&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static MutableFloatVector.Rel.Sparse<SIUnit> times(final FloatVector.Rel.Dense<?> left,
            final FloatVector.Rel.Sparse<?> right) throws ValueException
    {
        SIUnit targetUnit =
                Unit.lookupOrCreateSIUnitWithSICoefficients(SICoefficients.multiply(left.getUnit().getSICoefficients(),
                        right.getUnit().getSICoefficients()).toString());
        MutableFloatVector.Rel.Sparse<SIUnit> work =
                new MutableFloatVector.Rel.Sparse<SIUnit>(left.deepCopyOfData(), targetUnit);
        work.scaleValueByValue(right);
        return work;
    }

    /**
     * Multiply two FloatVectors value by value and store the result in a new
     * MutableFloatVector.Rel.Sparse&lt;SIUnit&gt;.
     * @param left FloatVector.Rel.Sparse&lt;?&gt;; the left operand
     * @param right FloatVector.Rel&lt;?&gt;; the right operand
     * @return MutableFloatVector.Rel.Sparse&lt;SIUnit&gt;
     * @throws ValueException when the vectors do not have the same size
     */
    public static MutableFloatVector.Rel.Sparse<SIUnit> times(final FloatVector.Rel.Sparse<?> left,
            final FloatVector.Rel<?> right) throws ValueException
    {
        SIUnit targetUnit =
                Unit.lookupOrCreateSIUnitWithSICoefficients(SICoefficients.multiply(left.getUnit().getSICoefficients(),
                        right.getUnit().getSICoefficients()).toString());
        MutableFloatVector.Rel.Sparse<SIUnit> work =
                new MutableFloatVector.Rel.Sparse<SIUnit>(left.deepCopyOfData(), targetUnit);
        work.scaleValueByValue(right);
        return work;
    }

    /**
     * Multiply the values in a FloatVector and a float array value by value and store the result in a new
     * MutableFloatVector.Abs.Dense&lt;U&gt;.
     * @param left FloatVector.Abs.Dense&lt;U&gt;; the FloatVector
     * @param right float[]; the float array
     * @param <U> Unit; the unit of the left parameter and the result
     * @return MutableFloatVector.Abs.Dense&lt;U&gt;
     * @throws ValueException when the FloatVector and the array do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Abs.Dense<U> times(final FloatVector.Abs.Dense<U> left,
            final float[] right) throws ValueException
    {
        return (MutableFloatVector.Abs.Dense<U>) left.mutable().scaleValueByValue(right);
    }

    /**
     * Multiply the values in a FloatVector and a float array value by value and store the result in a new
     * MutableFloatVector.Abs.Sparse&lt;U&gt;.
     * @param left FloatVector.Abs.Sparse&lt;U&gt;; the FloatVector
     * @param right float[]; the float array
     * @param <U> Unit; the unit of the left parameter and the result
     * @return MutableFloatVector.Abs.Sparse&lt;U&gt;
     * @throws ValueException when the FloatVector and the array do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Abs.Sparse<U> times(final FloatVector.Abs.Sparse<U> left,
            final float[] right) throws ValueException
    {
        return (MutableFloatVector.Abs.Sparse<U>) left.mutable().scaleValueByValue(right);
    }

    /**
     * Multiply the values in a FloatVector and a float array value by value and store the result in a new
     * MutableFloatVector.Rel.Dense&lt;U&gt;.
     * @param left FloatVector.Rel.Dense&lt;U&gt;; the FloatVector
     * @param right float[]; the float array
     * @param <U> Unit; the unit of the left parameter and the result
     * @return MutableFloatVector.Rel.Dense&lt;U&gt;
     * @throws ValueException when the FloatVector and the array do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Dense<U> times(final FloatVector.Rel.Dense<U> left,
            final float[] right) throws ValueException
    {
        return (MutableFloatVector.Rel.Dense<U>) left.mutable().scaleValueByValue(right);
    }

    /**
     * Multiply the values in a FloatVector and a float array value by value and store the result in a new
     * MutableFloatVector.Rel.Sparse&lt;U&gt;.
     * @param left FloatVector.Rel.Sparse&lt;U&gt;; the FloatVector
     * @param right float[]; the float array
     * @param <U> Unit; the unit of the left parameter and the result
     * @return MutableFloatVector.Rel.Sparse&lt;U&gt;
     * @throws ValueException when the FloatVector and the array do not have the same size
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Sparse<U> times(final FloatVector.Rel.Sparse<U> left,
            final float[] right) throws ValueException
    {
        return (MutableFloatVector.Rel.Sparse<U>) left.mutable().scaleValueByValue(right);
    }

    /**
     * Make the Sparse equivalent of a DenseFloatMatrix1D.
     * @param dense FloatMatrix1D; the Dense FloatMatrix1D
     * @return SparseFloatMatrix1D
     */
    private static SparseFloatMatrix1D makeSparse(final FloatMatrix1D dense)
    {
        SparseFloatMatrix1D result = new SparseFloatMatrix1D((int) dense.size());
        result.assign(dense);
        return result;
    }

    /**
     * Create a Sparse version of a Dense FloatVector.
     * @param in FloatVector.Abs.Dense&lt;U&gt;; the Dense FloatVector
     * @param <U> Unit; the unit of the parameter and the result
     * @return MutableFloatVector.Abs.Sparse&lt;U&gt;
     */
    public static <U extends Unit<U>> MutableFloatVector.Abs.Sparse<U> denseToSparse(final FloatVector.Abs.Dense<U> in)
    {
        return new MutableFloatVector.Abs.Sparse<U>(makeSparse(in.getVectorSI()), in.getUnit());
    }

    /**
     * Create a Sparse version of a Dense FloatVector.
     * @param in FloatVector.Rel.Dense&lt;U&gt;; the Dense FloatVector
     * @param <U> Unit; the unit of the parameter and the result
     * @return MutableFloatVector.Rel.Sparse&lt;U&gt;
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Sparse<U> denseToSparse(final FloatVector.Rel.Dense<U> in)
    {
        return new MutableFloatVector.Rel.Sparse<U>(makeSparse(in.getVectorSI()), in.getUnit());
    }

    /**
     * Make the Dense equivalent of a SparseFloatMatrix1D.
     * @param sparse FloatMatrix1D; the Sparse FloatMatrix1D
     * @return DenseFloatMatrix1D
     */
    private static DenseFloatMatrix1D makeDense(final FloatMatrix1D sparse)
    {
        DenseFloatMatrix1D result = new DenseFloatMatrix1D((int) sparse.size());
        result.assign(sparse);
        return result;
    }

    /**
     * Create a Dense version of a Sparse FloatVector.
     * @param in FloatVector.Abs.Sparse&lt;U&gt;; the Sparse FloatVector
     * @param <U> Unit; the unit of the parameter and the result
     * @return MutableFloatVector.Abs.Dense&lt;U&gt;
     */
    public static <U extends Unit<U>> MutableFloatVector.Abs.Dense<U> sparseToDense(final FloatVector.Abs.Sparse<U> in)
    {
        return new MutableFloatVector.Abs.Dense<U>(makeDense(in.getVectorSI()), in.getUnit());
    }

    /**
     * Create a Dense version of a Sparse FloatVector.
     * @param in FloatVector.Rel.Sparse&lt;U&gt;; the Sparse FloatVector
     * @param <U> Unit; the unit of the parameter and the result
     * @return MutableFloatVector.Rel.Dense&lt;U&gt;
     */
    public static <U extends Unit<U>> MutableFloatVector.Rel.Dense<U> sparseToDense(final FloatVector.Rel.Sparse<U> in)
    {
        return new MutableFloatVector.Rel.Dense<U>(makeDense(in.getVectorSI()), in.getUnit());
    }

}
