//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.03 at 01:02:34 PM CET
//

package org.opentrafficsim.road.network.factory.vissim.xsd;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://www.opentrafficsim.org/ots}DEFINITIONS" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.w3.org/2001/XInclude}include" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.opentrafficsim.org/ots}NODE" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.opentrafficsim.org/ots}LINK" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.opentrafficsim.org/ots}ROUTE" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.opentrafficsim.org/ots}ROUTEMIX" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.opentrafficsim.org/ots}SHORTESTROUTE" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.opentrafficsim.org/ots}SHORTESTROUTEMIX" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"definitionsOrIncludeOrNODE"})
@XmlRootElement(name = "NETWORK")
public class NETWORK
{

    @XmlElements({@XmlElement(name = "DEFINITIONS", type = DEFINITIONS.class),
            @XmlElement(name = "include", namespace = "http://www.w3.org/2001/XInclude", type = IncludeType.class),
            @XmlElement(name = "NODE", type = NODE.class), @XmlElement(name = "LINK", type = LINK.class),
            @XmlElement(name = "ROUTE", type = ROUTE.class), @XmlElement(name = "ROUTEMIX", type = ROUTEMIX.class),
            @XmlElement(name = "SHORTESTROUTE", type = SHORTESTROUTE.class),
            @XmlElement(name = "SHORTESTROUTEMIX", type = SHORTESTROUTEMIX.class)})
    protected List<Object> definitionsOrIncludeOrNODE;

    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;

    /**
     * Gets the value of the definitionsOrIncludeOrNODE property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * definitionsOrIncludeOrNODE property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getDEFINITIONSOrIncludeOrNODE().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DEFINITIONS } {@link IncludeType } {@link NODE }
     * {@link LINK } {@link ROUTE } {@link ROUTEMIX } {@link SHORTESTROUTE } {@link SHORTESTROUTEMIX }
     */
    /**
     * @return definitions
     */
    public List<Object> getDEFINITIONSOrIncludeOrNODE()
    {
        if (definitionsOrIncludeOrNODE == null)
        {
            definitionsOrIncludeOrNODE = new ArrayList<Object>();
        }
        return this.definitionsOrIncludeOrNODE;
    }

    /**
     * Gets the value of the base property.
     * @return possible object is {@link String }
     */
    public String getBase()
    {
        return base;
    }

    /**
     * Sets the value of the base property.
     * @param value String; allowed object is {@link String }
     */
    public void setBase(String value)
    {
        this.base = value;
    }

}
