package org.opentrafficsim.road.gtu.lane.tactical.mirova.core.util;

import java.util.Collections;
import java.util.List;

/**
 * Arbitration strategy that selects the plan with the highest utility score.
 * <p>
 * Because operational plans contain fixed spatial paths, this "winner-takes-all" approach ensures
 * physical safety by preventing the blending of mutually exclusive spatial trajectories.
 * </p>
 * <p>
 * Copyright (c) 2026 Marvin Baumann / KIT. All rights reserved. <br>
 * BSD-style license. See <a href="https://opentrafficsim.org/docs/license.html">OpenTrafficSim License</a>.
 * </p>
 * @author <a href="https://github.com/baumarv">Marvin Baumann</a>
 */
public class MaxUtilityArbitrator implements PlanArbitrator
{
    /**
     * Selects the plan with the maximum utility score.
     * * @param proposedPlans List&lt;ScoredOperationalPlan&gt;; a list of plans generated by active maneuver patterns
     * @return ScoredOperationalPlan; the plan holding the highest utility
     * @throws IllegalArgumentException if the provided list of plans is null or empty
     */
    @Override
    public ScoredOperationalPlan arbitrate(final List<ScoredOperationalPlan> proposedPlans) throws IllegalArgumentException
    {
        if (proposedPlans == null || proposedPlans.isEmpty())
        {
            throw new IllegalArgumentException("Cannot arbitrate an empty or null list of proposed plans.");
        }

        return Collections.max(proposedPlans);
    }
}