package org.opentrafficsim.road.gtu.lane.tactical.mirova.core.util;

import java.util.List;

/**
 * Interface for operational plan arbitration strategies.
 * <p>
 * Implementations of this interface are responsible for selecting a single plan out of a list
 * of concurrently generated proposals from various maneuver patterns.
 * </p>
 * <p>
 * Copyright (c) 2026 Marvin Baumann / KIT. All rights reserved. <br>
 * BSD-style license. See <a href="https://opentrafficsim.org/docs/license.html">OpenTrafficSim License</a>.
 * </p>
 * @author <a href="https://github.com/baumarv">Marvin Baumann</a>
 */
public interface PlanArbitrator
{
    /**
     * Selects the most appropriate plan from the given list of scored proposals.
     * * @param proposedPlans List&lt;ScoredOperationalPlan&gt;; a list of plans generated by active maneuver patterns
     * @return ScoredOperationalPlan; the selected plan that should be executed by the GTU
     * @throws IllegalArgumentException if the provided list of plans is null or empty
     */
    ScoredOperationalPlan arbitrate(List<ScoredOperationalPlan> proposedPlans) throws IllegalArgumentException;
}